// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This proto definition describes an interface layer of a device.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: go.chromium.org/infra/libs/fleet/device_labels.proto

package fleet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NEXT TAG: 3
type ResourceType int32

const (
	ResourceType_RESOURCETYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RESOURCETYPE_CROS        ResourceType = 1
	ResourceType_RESOURCETYPE_BROWSER     ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCETYPE_UNSPECIFIED",
		1: "RESOURCETYPE_CROS",
		2: "RESOURCETYPE_BROWSER",
	}
	ResourceType_value = map[string]int32{
		"RESOURCETYPE_UNSPECIFIED": 0,
		"RESOURCETYPE_CROS":        1,
		"RESOURCETYPE_BROWSER":     2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_go_chromium_org_infra_libs_fleet_device_labels_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescGZIP(), []int{0}
}

// NEXT TAG: 5
type DeviceLabel_SOURCE int32

const (
	DeviceLabel_SOURCE_UNSPECIFIED   DeviceLabel_SOURCE = 0
	DeviceLabel_SOURCE_HART          DeviceLabel_SOURCE = 1
	DeviceLabel_SOURCE_HWID_SERVER   DeviceLabel_SOURCE = 2
	DeviceLabel_SOURCE_MANUAL_INPUT  DeviceLabel_SOURCE = 3
	DeviceLabel_SOURCE_AUTO_DETECTED DeviceLabel_SOURCE = 4
)

// Enum value maps for DeviceLabel_SOURCE.
var (
	DeviceLabel_SOURCE_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_HART",
		2: "SOURCE_HWID_SERVER",
		3: "SOURCE_MANUAL_INPUT",
		4: "SOURCE_AUTO_DETECTED",
	}
	DeviceLabel_SOURCE_value = map[string]int32{
		"SOURCE_UNSPECIFIED":   0,
		"SOURCE_HART":          1,
		"SOURCE_HWID_SERVER":   2,
		"SOURCE_MANUAL_INPUT":  3,
		"SOURCE_AUTO_DETECTED": 4,
	}
)

func (x DeviceLabel_SOURCE) Enum() *DeviceLabel_SOURCE {
	p := new(DeviceLabel_SOURCE)
	*p = x
	return p
}

func (x DeviceLabel_SOURCE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceLabel_SOURCE) Descriptor() protoreflect.EnumDescriptor {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_enumTypes[1].Descriptor()
}

func (DeviceLabel_SOURCE) Type() protoreflect.EnumType {
	return &file_go_chromium_org_infra_libs_fleet_device_labels_proto_enumTypes[1]
}

func (x DeviceLabel_SOURCE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceLabel_SOURCE.Descriptor instead.
func (DeviceLabel_SOURCE) EnumDescriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescGZIP(), []int{1, 0}
}

// NEXT TAG: 3
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceLabels  []*DeviceLabel         `protobuf:"bytes,1,rep,name=device_labels,json=deviceLabels,proto3" json:"device_labels,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=fleet.device.labels.ResourceType" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetDeviceLabels() []*DeviceLabel {
	if x != nil {
		return x.DeviceLabels
	}
	return nil
}

func (x *Device) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCETYPE_UNSPECIFIED
}

// NEXT TAG: 7
type DeviceLabel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generic name of this label;
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The id used in scheduling layer;
	SchedulableId string `protobuf:"bytes,2,opt,name=schedulable_id,json=schedulableId,proto3" json:"schedulable_id,omitempty"`
	// The value of labels used in scheduling layer;
	SchedulableValue *SchedulableValue `protobuf:"bytes,3,opt,name=schedulable_value,json=schedulableValue,proto3" json:"schedulable_value,omitempty"`
	// The source of this device label;
	Source DeviceLabel_SOURCE `protobuf:"varint,4,opt,name=source,proto3,enum=fleet.device.labels.DeviceLabel_SOURCE" json:"source,omitempty"`
	// The owner of this device label;
	Owner string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	// The reason to add this device label;
	ReasonToAdd   string `protobuf:"bytes,6,opt,name=reason_to_add,json=reasonToAdd,proto3" json:"reason_to_add,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceLabel) Reset() {
	*x = DeviceLabel{}
	mi := &file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLabel) ProtoMessage() {}

func (x *DeviceLabel) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLabel.ProtoReflect.Descriptor instead.
func (*DeviceLabel) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeviceLabel) GetSchedulableId() string {
	if x != nil {
		return x.SchedulableId
	}
	return ""
}

func (x *DeviceLabel) GetSchedulableValue() *SchedulableValue {
	if x != nil {
		return x.SchedulableValue
	}
	return nil
}

func (x *DeviceLabel) GetSource() DeviceLabel_SOURCE {
	if x != nil {
		return x.Source
	}
	return DeviceLabel_SOURCE_UNSPECIFIED
}

func (x *DeviceLabel) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeviceLabel) GetReasonToAdd() string {
	if x != nil {
		return x.ReasonToAdd
	}
	return ""
}

// Indicating the schedulable values, can be changed if the scheduling layer is changed.
type SchedulableValue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SwarmingLabels []string               `protobuf:"bytes,1,rep,name=swarming_labels,json=swarmingLabels,proto3" json:"swarming_labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedulableValue) Reset() {
	*x = SchedulableValue{}
	mi := &file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulableValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulableValue) ProtoMessage() {}

func (x *SchedulableValue) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulableValue.ProtoReflect.Descriptor instead.
func (*SchedulableValue) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescGZIP(), []int{2}
}

func (x *SchedulableValue) GetSwarmingLabels() []string {
	if x != nil {
		return x.SwarmingLabels
	}
	return nil
}

var File_go_chromium_org_infra_libs_fleet_device_labels_proto protoreflect.FileDescriptor

var file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDesc = string([]byte{
	0x0a, 0x34, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x06,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x46, 0x0a,
	0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x93, 0x03, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x52,
	0x0a, 0x11, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x10, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x27, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x2e, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x22, 0x7c, 0x0a,
	0x06, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x48, 0x41, 0x52, 0x54, 0x10, 0x01,
	0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x48, 0x57, 0x49, 0x44, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x5f, 0x4d, 0x41, 0x4e, 0x55, 0x41, 0x4c, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10,
	0x03, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x4f,
	0x5f, 0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x04, 0x22, 0x3b, 0x0a, 0x10, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x27, 0x0a, 0x0f, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x69,
	0x6e, 0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x2a, 0x5d, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x52, 0x45, 0x53, 0x4f,
	0x55, 0x52, 0x43, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x52, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x52,
	0x4f, 0x57, 0x53, 0x45, 0x52, 0x10, 0x02, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x6f, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x3b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescOnce sync.Once
	file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescData []byte
)

func file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescGZIP() []byte {
	file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescOnce.Do(func() {
		file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDesc), len(file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDesc)))
	})
	return file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDescData
}

var file_go_chromium_org_infra_libs_fleet_device_labels_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_go_chromium_org_infra_libs_fleet_device_labels_proto_goTypes = []any{
	(ResourceType)(0),        // 0: fleet.device.labels.ResourceType
	(DeviceLabel_SOURCE)(0),  // 1: fleet.device.labels.DeviceLabel.SOURCE
	(*Device)(nil),           // 2: fleet.device.labels.Device
	(*DeviceLabel)(nil),      // 3: fleet.device.labels.DeviceLabel
	(*SchedulableValue)(nil), // 4: fleet.device.labels.SchedulableValue
}
var file_go_chromium_org_infra_libs_fleet_device_labels_proto_depIdxs = []int32{
	3, // 0: fleet.device.labels.Device.device_labels:type_name -> fleet.device.labels.DeviceLabel
	0, // 1: fleet.device.labels.Device.resource_type:type_name -> fleet.device.labels.ResourceType
	4, // 2: fleet.device.labels.DeviceLabel.schedulable_value:type_name -> fleet.device.labels.SchedulableValue
	1, // 3: fleet.device.labels.DeviceLabel.source:type_name -> fleet.device.labels.DeviceLabel.SOURCE
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_go_chromium_org_infra_libs_fleet_device_labels_proto_init() }
func file_go_chromium_org_infra_libs_fleet_device_labels_proto_init() {
	if File_go_chromium_org_infra_libs_fleet_device_labels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDesc), len(file_go_chromium_org_infra_libs_fleet_device_labels_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_chromium_org_infra_libs_fleet_device_labels_proto_goTypes,
		DependencyIndexes: file_go_chromium_org_infra_libs_fleet_device_labels_proto_depIdxs,
		EnumInfos:         file_go_chromium_org_infra_libs_fleet_device_labels_proto_enumTypes,
		MessageInfos:      file_go_chromium_org_infra_libs_fleet_device_labels_proto_msgTypes,
	}.Build()
	File_go_chromium_org_infra_libs_fleet_device_labels_proto = out.File
	file_go_chromium_org_infra_libs_fleet_device_labels_proto_goTypes = nil
	file_go_chromium_org_infra_libs_fleet_device_labels_proto_depIdxs = nil
}
