#!/bin/bash -e

labpackInstance=chromiumos/infra/labpack/linux-amd64
parisInstance=experimental/infra/paris/linux-amd64


function get_instance_id() {
	echo $(cipd describe -version $2 $1 | awk -F ': +' '/Instance ID:/{print $2}')
}
function get_git_revision() {
	echo $(cipd describe -version $2 $1 | awk -F ':' '/git_revision/{print $2; exit}')
}
function get_data() {
	echo $(get_instance_id $1 $2) $(get_git_revision $1 $2)
}

echo "Get the latest labpack CIPD and git information..."
read labpack_latest_id lapback_latest_git < <(get_data $labpackInstance "latest")
read labpack_prod_id labpack_prod_git < <(get_data $labpackInstance "prod")

git fetch origin main
labpack_changelist=$(git log refs/remotes/origin/main --oneline ${prod_git}..${latest_git} -- . ../../recovery)


echo "Get the latest paris CIPD and git information..."
read paris_latest_id paris_latest_git < <(get_data $parisInstance "latest")
read paris_prod_id paris_prod_git < <(get_data $parisInstance "prod")

git fetch origin main
paris_changelist=$(git log refs/remotes/origin/main --oneline ${paris_prod_git}..${paris_latest_git} -- . ../../cmd/paris)


cat <<EOF
The push will includes below changes:

$labpack_changelist

$paris_changelist


Are they good? [y/n]
EOF

read confirm

if [[ "${confirm}" != "y" ]]; then
	echo "Aborting the push"
	exit 1
fi

cipd set-ref -ref prev-prod -version prod ${labpackInstance}
cipd set-ref -ref prod -version ${labpack_latest_id} ${labpackInstance}
cipd set-ref -ref prev-prod -version prod ${parisInstance}
cipd set-ref -ref prod -version ${paris_latest_id} ${parisInstance}

cat <<EOF
Don't forget to send out an announcement!
To:
chromeos-infra-releases@google.com

Title:
PARIS push to prod(${latest_git})

Content:
Previous CIPD instance id: ${prod_id}

New CIPD instance id: ${latest_id}

Change-list:
${changelist}
EOF
