# Copyright 2025 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

FROM haproxy:latest

COPY shivas /

# Use the default entrypoint from the base haproxy image.
