# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

version: "2"

# https://golangci-lint.run/usage/configuration/#linters-configuration
linters:
  enable:
    - copyloopvar
    - errorlint
    - intrange
    - noctx
    - gomodguard
    - govet
  disable:
    # There are also many unchecked errors.
    - errcheck
  settings:
    # TODO(gregorynisbet): Use default config here.
    errorlint:
      # Moving %v or %s to %w is a breaking API change.
      errorf: false
      # type switches on errors are okay (for now)
      asserts: false
      # == is okay on errors (for now)
      comparison: false
    # prevent direct dependencies on bad modules.
    # Write this stanza in JSON syntax, it's more readable anyway.
    gomodguard: {
      "blocked": {
        "modules": [
          {
            "github.com/smartystreets/goconvey": {
              "reason": "see go/noconvey-psa for more information",
              "recommendations": ["go.chromium.org/luci/common/testing/ftt"]
            }
          }
        ]
      }
    }
    staticcheck:
      checks:
        - all
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        # Aboves are default set of checks in golangci-lint.
        # Belows are additional checks we currently need to disable in infra repo.
        # https://staticcheck.dev/docs/checks#QF1003
        # Convert if/else-if chain to tagged switch
        - "-QF1003"
        # https://staticcheck.dev/docs/checks#QF1006
        # Lift if + break into loop condition
        - "-QF1006"
        # https://staticcheck.dev/docs/checks#QF1007
        # Merge conditional assignment into variable declaration
        - "-QF1007"
        # https://staticcheck.dev/docs/checks#QF1008
        # Omit embedded fields from selector expression
        - "-QF1008"
        # https://staticcheck.dev/docs/checks#QF1012
        # Use fmt.Fprintf(x, ...) instead of x.Write(fmt.Sprintf(...))
        - "-QF1012"
        # https://staticcheck.dev/docs/checks#S1038
        # Unnecessarily complex way of printing formatted string
        - "-S1038"
        # https://staticcheck.dev/docs/checks#SA1006
        # Printf with dynamic first argument and no further arguments
        - "-SA1006"
        # https://staticcheck.dev/docs/checks#SA1019
        # Using a deprecated function, variable, constant or field
        - "-SA1019"
        # https://staticcheck.dev/docs/checks#SA1029
        # Inappropriate key in call to context.WithValue
        - "-SA1029"
        # https://staticcheck.dev/docs/checks#SA4006
        # A value assigned to a variable is never read before being overwritten. Forgotten error check or dead code?
        - "-SA4006"
        # https://staticcheck.dev/docs/checks#SA4010
        # The result of append will never be observed anywhere
        - "-SA4010"
        # https://staticcheck.dev/docs/checks#SA5001
        # Deferring Close before checking for a possible error
        - "-SA5001"
        # https://staticcheck.dev/docs/checks#SA9003
        # Empty body in an if or else branch
        - "-SA9003"
        # https://staticcheck.dev/docs/checks#ST1005
        # Incorrectly formatted error string
        - "-ST1005"
        # https://staticcheck.dev/docs/checks#ST1011
        # Poorly chosen name for variable of type time.Duration
        - "-ST1011"
        # https://staticcheck.dev/docs/checks#ST1012
        # Poorly chosen name for error variable
        - "-ST1012"

  exclusions:
    # Independently from option `exclude` we use default exclude patterns,
    # it can be disabled by this option. To list all
    # excluded by default patterns execute `golangci-lint run --help`.
    # The old `exclude-use-default: false` setting implied manual control, reflected here.
    rules:
      - path: (.+)\.go$
        # Exclude specific error checking patterns
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: cmd/cros_test_platform/luciexe/execute/execute_test.go|cros/cmd/cft/dut/cros-dut/dutssh/unix_socket_bridge.go
        # https://staticcheck.dev/docs/checks#S1000
        # Use plain channel send or receive instead of single-case select
        text: "^S1000: "
      - linters:
        - unused
        # Ignore `_kind` field in struct for datastore.
        text: "field _kind is unused"
      # TODO(b/398333401): Reduce this exclude by cleaning up unused symbols.
      - linters:
        - unused
        path: ^(appengine/(cr-rev|cros|crosskylabadmin|dashboard|drone-queen|poros|rietveld-static|rubber-stamper|sheriff-o-matic|test-results|tree-status)|chromeperf|cmd|chromium|cr_builder_health|cros|device_manager|experimental|fleetconsole|libs|qscheduler|rts|tools|unifiedfleet|vm_leaser)/
      # TODO(b/398333401): Reduce this exclude by cleaning up ineffective assignments.
      - linters:
        - ineffassign
        path: ^(appengine/(cros|poros|rotation-proxy)|chromeperf|cmd|cr_builder_health|cros|experimental|qscheduler|rts|tools|unifiedfleet)/
      # See https://chromium-review.googlesource.com/c/infra/infra/+/6490573 and https://chromium-review.googlesource.com/c/infra/infra/+/6284947 for details.
      # golangbuild intentionally does not wrap certain errors.
      # TODO(gregorynisbet): Drop this stanza when go1.23 support is dropped + 1 month-ish.
      - linters:
        - errorlint
        path: ^experimental/golangbuild
      # TODO(gregorynisbet): Reduce this exclude by cleaning up instances where the context should be passed.
      - linters:
        - noctx
        path: ^(appengine|build|cros|cmd|chromeperf|fleetconsole|monorail|tools|tricium)
    paths:
      # Ignore files under third_party dir.
      - ^third_party/.*\.go$
      # TODO(gregorynisbet): remove this exemption too.
      - ^cros/cmd/cros_test_runner/internal/executors/generic_provision_executor.go$
      # TODO(gregorynisbet): remove this exemption too.
      - ^cros/cmd/k8s-management/metrics/pod_perf_cmd.go$
      # TODO(gregorynisbet): remove this exemption too.
      - ^cros/internal/branch/helper.go$
      # TODO(gregorynisbet): remove this exemption too.
      - ^qscheduler/service/app/state/batchrunner.go$
      # TODO(gregorynisbet): remove this exemption after https://chromium-review.googlesource.com/c/infra/infra/+/6581399 lands
      - ^cros/cmd/ctpv2/internal/commands/schedule_tasks.go$
      # TODO(gregorynisbet): BEGIN remove after https://chromium-review.googlesource.com/c/infra/infra/+/6580823 lands
      - ^cros/cmd/cft/execution/cros-test/internal/driver/tradefed_nonxts_command_builder.go$
      - ^cros/cmd/cft/execution/cros-test/internal/driver/tradefed_xts_command_builder.go$
      - ^cros/cmd/ctpv2/internal/commands/generate_trv2_requests_helper.go$
      - ^cros/cmd/kron/builds/ingest.go$
      # TODO(gregorynisbet): END remove after https://chromium-review.googlesource.com/c/infra/infra/+/6580823 lands

      # TODO(gregorynisbet): BEGIN copylock issue files.
      - appengine/rotation-proxy/rotation_proxy_server.go
      - cmd/bqexport/test_data/main.go
      - cros/cmd/cros-tool-runner/internal/v2/templates/placeholder.go
      - cros/cmd/cros-tool-runner/internal/v2/templates/placeholder_test.go
      - cros/cmd/cros-tool-runner/internal/v2/templates/template_cros_provision.go
      - cros/cmd/cros-tool-runner/internal/v2/templates/template_cros_provision_test.go
      - cros/cmd/ctpv2/internal/commands/middle_out_cmd.go
      - cros/lib/buildbucket/properties_test.go
      - libs/fleet/boxster/swarming/convert_test.go
      - monorail/endpoints_test.go
      - tools/vpython/legacy/vpython2.7/luci/application/application.go
      - tools/vpython/legacy/vpython2.7/luci/application/subcommand_delete.go
      - tools/vpython/legacy/vpython2.7/luci/application/subcommand_install.go
      - tools/vpython/legacy/vpython2.7/luci/run.go
      - tools/vpython/legacy/vpython2.7/luci/spec/spec_test.go
      - tools/vpython/legacy/vpython2.7/luci/venv/config.go
      - tools/vpython/legacy/vpython2.7/luci/venv/venv.go
      - tools/vpython/legacy/vpython2.7/luci/venv/venv_resources_test.go
      - tools/vpython/legacy/vpython2.7/luci/venv/venv_test.go
      # TODO(gregorynisbet): END copylock issue files.


# https://golangci-lint.run/usage/configuration/#issues-configuration
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false

formatters:
  enable:
    - gci
  settings:
    # https://golangci-lint.run/usage/formatters/#gci
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot`,
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        # Standard section: captures all standard packages.
        - standard
        # Default section: contains all imports that could not be matched to another section type.
        - default
        # Custom section: groups all imports with the specified Prefix.
        - prefix(go.chromium.org)
        # Custom section: groups all imports with the specified Prefix (local modules).
        - localmodule
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
