// Code generated by MockGen. DO NOT EDIT.
// Source: invocations.go

// Package mock_androidapi is a generated GoMock package.
package mock_androidapi

import (
	context "context"
	androidapi "go.chromium.org/infra/cros/cmd/common_lib/android_api"
	androidbuildinternal "go.chromium.org/infra/cros/cmd/common_lib/ants/androidbuildinternal/v3"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInvocationService is a mock of InvocationService interface.
type MockInvocationService struct {
	ctrl     *gomock.Controller
	recorder *MockInvocationServiceMockRecorder
}

// MockInvocationServiceMockRecorder is the mock recorder for MockInvocationService.
type MockInvocationServiceMockRecorder struct {
	mock *MockInvocationService
}

// NewMockInvocationService creates a new mock instance.
func NewMockInvocationService(ctrl *gomock.Controller) *MockInvocationService {
	mock := &MockInvocationService{ctrl: ctrl}
	mock.recorder = &MockInvocationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvocationService) EXPECT() *MockInvocationServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockInvocationService) Get(ctx context.Context, resourceID string) (*androidbuildinternal.Invocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceID)
	ret0, _ := ret[0].(*androidbuildinternal.Invocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInvocationServiceMockRecorder) Get(ctx, resourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInvocationService)(nil).Get), ctx, resourceID)
}

// Insert mocks base method.
func (m *MockInvocationService) Insert(invocation *androidbuildinternal.Invocation) (*androidbuildinternal.Invocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", invocation)
	ret0, _ := ret[0].(*androidbuildinternal.Invocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockInvocationServiceMockRecorder) Insert(invocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockInvocationService)(nil).Insert), invocation)
}

// List mocks base method.
func (m *MockInvocationService) List(ctx context.Context, invocationID string, options androidapi.AndroidBuildAPIOptions) (*androidbuildinternal.InvocationListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, invocationID, options)
	ret0, _ := ret[0].(*androidbuildinternal.InvocationListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInvocationServiceMockRecorder) List(ctx, invocationID, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvocationService)(nil).List), ctx, invocationID, options)
}

// Patch mocks base method.
func (m *MockInvocationService) Patch(resourceID string, invocation *androidbuildinternal.Invocation) (*androidbuildinternal.Invocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", resourceID, invocation)
	ret0, _ := ret[0].(*androidbuildinternal.Invocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockInvocationServiceMockRecorder) Patch(resourceID, invocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockInvocationService)(nil).Patch), resourceID, invocation)
}

// Update mocks base method.
func (m *MockInvocationService) Update(resourceID string, invocation *androidbuildinternal.Invocation) (*androidbuildinternal.Invocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", resourceID, invocation)
	ret0, _ := ret[0].(*androidbuildinternal.Invocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInvocationServiceMockRecorder) Update(resourceID, invocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvocationService)(nil).Update), resourceID, invocation)
}
