// Code generated by MockGen. DO NOT EDIT.
// Source: workunits.go

// Package mock_androidapi is a generated GoMock package.
package mock_androidapi

import (
	context "context"
	androidapi "go.chromium.org/infra/cros/cmd/common_lib/android_api"
	androidbuildinternal "go.chromium.org/infra/cros/cmd/common_lib/ants/androidbuildinternal/v3"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkUnitService is a mock of WorkUnitService interface.
type MockWorkUnitService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkUnitServiceMockRecorder
}

// MockWorkUnitServiceMockRecorder is the mock recorder for MockWorkUnitService.
type MockWorkUnitServiceMockRecorder struct {
	mock *MockWorkUnitService
}

// NewMockWorkUnitService creates a new mock instance.
func NewMockWorkUnitService(ctrl *gomock.Controller) *MockWorkUnitService {
	mock := &MockWorkUnitService{ctrl: ctrl}
	mock.recorder = &MockWorkUnitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkUnitService) EXPECT() *MockWorkUnitServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWorkUnitService) Get(resourceID string) (*androidbuildinternal.WorkUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", resourceID)
	ret0, _ := ret[0].(*androidbuildinternal.WorkUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorkUnitServiceMockRecorder) Get(resourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkUnitService)(nil).Get), resourceID)
}

// Insert mocks base method.
func (m *MockWorkUnitService) Insert(workunit *androidbuildinternal.WorkUnit) (*androidbuildinternal.WorkUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", workunit)
	ret0, _ := ret[0].(*androidbuildinternal.WorkUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockWorkUnitServiceMockRecorder) Insert(workunit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWorkUnitService)(nil).Insert), workunit)
}

// List mocks base method.
func (m *MockWorkUnitService) List(ctx context.Context, invocationID string, options androidapi.AndroidBuildAPIOptions) (*androidbuildinternal.WorkUnitListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, invocationID, options)
	ret0, _ := ret[0].(*androidbuildinternal.WorkUnitListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkUnitServiceMockRecorder) List(ctx, invocationID, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkUnitService)(nil).List), ctx, invocationID, options)
}

// Patch mocks base method.
func (m *MockWorkUnitService) Patch(resourceID string, workunit *androidbuildinternal.WorkUnit) (*androidbuildinternal.WorkUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", resourceID, workunit)
	ret0, _ := ret[0].(*androidbuildinternal.WorkUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockWorkUnitServiceMockRecorder) Patch(resourceID, workunit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockWorkUnitService)(nil).Patch), resourceID, workunit)
}

// Update mocks base method.
func (m *MockWorkUnitService) Update(resourceID string, workunit *androidbuildinternal.WorkUnit) (*androidbuildinternal.WorkUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", resourceID, workunit)
	ret0, _ := ret[0].(*androidbuildinternal.WorkUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkUnitServiceMockRecorder) Update(resourceID, workunit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkUnitService)(nil).Update), resourceID, workunit)
}
