// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package scheduling.api;

import "go.chromium.org/luci/buildbucket/proto/builds_service.proto";

option go_package = "go.chromium.org/infra/libs/fleet/scheduling/api";

// Task contains a task ID and url provided by the backend.
message Task {
  int64 id = 1;
  string url = 2;
}

// ScheduleTaskRequest is the request for the TaskSchedulingAPI.ScheduleTask
// endpoint.
message ScheduleTaskRequest {
  // BuildBucket request to instantiate task.
  buildbucket.v2.ScheduleBuildRequest buildbucket_request = 2;
  // Device name. Refers to the Swarming dut_name or hostname.
  string device_name = 3;
}

// CancelTasksRequest is the request for the TaskSchedulingAPI.CancelTasks
// endpoint.
message CancelTasksRequest {
  repeated int64 task_ids = 2;
}
