// Copyright 2017 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: infra/tools/git/state/state.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State is the persistent wrapper state. It is exported by a Git wrapper
// process as encoded JSON using the "gitWrapperENV" environment variable.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SelfPath is the absolute path to the current process.
	SelfPath string `protobuf:"bytes,1,opt,name=self_path,json=selfPath,proto3" json:"self_path,omitempty"`
	// GitPath is the absolute path of the Git executable that was identified.
	GitPath string `protobuf:"bytes,2,opt,name=git_path,json=gitPath,proto3" json:"git_path,omitempty"`
	// Retrying, if true, means that we are running in the context of a previous
	// wrapper that is, itself, applying retry criteria.
	Retrying      bool `protobuf:"varint,3,opt,name=retrying,proto3" json:"retrying,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_infra_tools_git_state_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_infra_tools_git_state_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_infra_tools_git_state_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetSelfPath() string {
	if x != nil {
		return x.SelfPath
	}
	return ""
}

func (x *State) GetGitPath() string {
	if x != nil {
		return x.GitPath
	}
	return ""
}

func (x *State) GetRetrying() bool {
	if x != nil {
		return x.Retrying
	}
	return false
}

var File_infra_tools_git_state_state_proto protoreflect.FileDescriptor

var file_infra_tools_git_state_state_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x67, 0x69,
	0x74, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5b, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x69, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x69, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x69, 0x6e, 0x67, 0x42, 0x1d, 0x5a, 0x1b, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x67, 0x69, 0x74, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x3b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_infra_tools_git_state_state_proto_rawDescOnce sync.Once
	file_infra_tools_git_state_state_proto_rawDescData []byte
)

func file_infra_tools_git_state_state_proto_rawDescGZIP() []byte {
	file_infra_tools_git_state_state_proto_rawDescOnce.Do(func() {
		file_infra_tools_git_state_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infra_tools_git_state_state_proto_rawDesc), len(file_infra_tools_git_state_state_proto_rawDesc)))
	})
	return file_infra_tools_git_state_state_proto_rawDescData
}

var file_infra_tools_git_state_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_infra_tools_git_state_state_proto_goTypes = []any{
	(*State)(nil), // 0: state.State
}
var file_infra_tools_git_state_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infra_tools_git_state_state_proto_init() }
func file_infra_tools_git_state_state_proto_init() {
	if File_infra_tools_git_state_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infra_tools_git_state_state_proto_rawDesc), len(file_infra_tools_git_state_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_tools_git_state_state_proto_goTypes,
		DependencyIndexes: file_infra_tools_git_state_state_proto_depIdxs,
		MessageInfos:      file_infra_tools_git_state_state_proto_msgTypes,
	}.Build()
	File_infra_tools_git_state_state_proto = out.File
	file_infra_tools_git_state_state_proto_goTypes = nil
	file_infra_tools_git_state_state_proto_depIdxs = nil
}
