// Copyright 2017 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file *partially* describes Monorail API.
// It is derived from
// https://chromium.googlesource.com/infra/infra/+/f2e2a4d/appengine/monorail/services/api_svc_v1.py
// and
// https://chromium.googlesource.com/infra/infra/+/f2e2a4d/appengine/monorail/proto/api_pb2_v1.py

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: infra/tools/bugtemplate/template.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PriUnset Priority = 0
	Priority_P0       Priority = 1
	Priority_P1       Priority = 2
	Priority_P2       Priority = 3
	Priority_P3       Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PriUnset",
		1: "P0",
		2: "P1",
		3: "P2",
		4: "P3",
	}
	Priority_value = map[string]int32{
		"PriUnset": 0,
		"P0":       1,
		"P1":       2,
		"P2":       3,
		"P3":       4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_infra_tools_bugtemplate_template_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_infra_tools_bugtemplate_template_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_infra_tools_bugtemplate_template_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_TypeUnset Type = 0
	Type_Bug       Type = 1
	Type_Feature   Type = 2
	Type_Task      Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TypeUnset",
		1: "Bug",
		2: "Feature",
		3: "Task",
	}
	Type_value = map[string]int32{
		"TypeUnset": 0,
		"Bug":       1,
		"Feature":   2,
		"Task":      3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_infra_tools_bugtemplate_template_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_infra_tools_bugtemplate_template_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_infra_tools_bugtemplate_template_proto_rawDescGZIP(), []int{1}
}

// A monorail issue template.
type Template struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A one line description of the issue.
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// The text body of the issue.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Emails of people participating in the issue discussion.
	Cc []string `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	// Monorail components for this issue.
	Components []string `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	// Issue priority.
	Pri Priority `protobuf:"varint,5,opt,name=pri,proto3,enum=bugtemplate.Priority" json:"pri,omitempty"`
	// Issue type.
	Type Type `protobuf:"varint,6,opt,name=type,proto3,enum=bugtemplate.Type" json:"type,omitempty"`
	// Bug labels.
	Labels []string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	// Bugs which should be blocked on the one being filed.
	// Supports "project:number" notation.
	Blocking      []string `protobuf:"bytes,8,rep,name=blocking,proto3" json:"blocking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_infra_tools_bugtemplate_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_infra_tools_bugtemplate_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_infra_tools_bugtemplate_template_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Template) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Template) GetPri() Priority {
	if x != nil {
		return x.Pri
	}
	return Priority_PriUnset
}

func (x *Template) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TypeUnset
}

func (x *Template) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Template) GetBlocking() []string {
	if x != nil {
		return x.Blocking
	}
	return nil
}

var File_infra_tools_bugtemplate_template_proto protoreflect.FileDescriptor

var file_infra_tools_bugtemplate_template_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x62, 0x75,
	0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x75, 0x67, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0xfa, 0x01, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x63, 0x63, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x63, 0x63, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x27,
	0x0a, 0x03, 0x70, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x62, 0x75,
	0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x52, 0x03, 0x70, 0x72, 0x69, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x62, 0x75, 0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x2a, 0x38, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x72, 0x69, 0x55, 0x6e, 0x73, 0x65, 0x74, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x50, 0x30, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x31, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02,
	0x50, 0x32, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x33, 0x10, 0x04, 0x2a, 0x35, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x73, 0x65,
	0x74, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75, 0x67, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x61, 0x73,
	0x6b, 0x10, 0x03, 0x42, 0x20, 0x5a, 0x1e, 0x2e, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x74,
	0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x62, 0x75, 0x67, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_infra_tools_bugtemplate_template_proto_rawDescOnce sync.Once
	file_infra_tools_bugtemplate_template_proto_rawDescData []byte
)

func file_infra_tools_bugtemplate_template_proto_rawDescGZIP() []byte {
	file_infra_tools_bugtemplate_template_proto_rawDescOnce.Do(func() {
		file_infra_tools_bugtemplate_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infra_tools_bugtemplate_template_proto_rawDesc), len(file_infra_tools_bugtemplate_template_proto_rawDesc)))
	})
	return file_infra_tools_bugtemplate_template_proto_rawDescData
}

var file_infra_tools_bugtemplate_template_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_infra_tools_bugtemplate_template_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_infra_tools_bugtemplate_template_proto_goTypes = []any{
	(Priority)(0),    // 0: bugtemplate.Priority
	(Type)(0),        // 1: bugtemplate.Type
	(*Template)(nil), // 2: bugtemplate.Template
}
var file_infra_tools_bugtemplate_template_proto_depIdxs = []int32{
	0, // 0: bugtemplate.Template.pri:type_name -> bugtemplate.Priority
	1, // 1: bugtemplate.Template.type:type_name -> bugtemplate.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_infra_tools_bugtemplate_template_proto_init() }
func file_infra_tools_bugtemplate_template_proto_init() {
	if File_infra_tools_bugtemplate_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infra_tools_bugtemplate_template_proto_rawDesc), len(file_infra_tools_bugtemplate_template_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_tools_bugtemplate_template_proto_goTypes,
		DependencyIndexes: file_infra_tools_bugtemplate_template_proto_depIdxs,
		EnumInfos:         file_infra_tools_bugtemplate_template_proto_enumTypes,
		MessageInfos:      file_infra_tools_bugtemplate_template_proto_msgTypes,
	}.Build()
	File_infra_tools_bugtemplate_template_proto = out.File
	file_infra_tools_bugtemplate_template_proto_goTypes = nil
	file_infra_tools_bugtemplate_template_proto_depIdxs = nil
}
