// Copyright 2017 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: go.chromium.org/infra/appengine/dashboard/api/dashboard/dashboard.proto

package dashboard

import prpc "go.chromium.org/luci/grpc/prpc"

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_UNDEFINED Severity = 0
	Severity_RED       Severity = 1
	Severity_YELLOW    Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "UNDEFINED",
		1: "RED",
		2: "YELLOW",
	}
	Severity_value = map[string]int32{
		"UNDEFINED": 0,
		"RED":       1,
		"YELLOW":    2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{0}
}

type UpdateOpenIncidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChopsService  *ChopsService          `protobuf:"bytes,1,opt,name=chops_service,json=chopsService,proto3" json:"chops_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOpenIncidentsRequest) Reset() {
	*x = UpdateOpenIncidentsRequest{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOpenIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpenIncidentsRequest) ProtoMessage() {}

func (x *UpdateOpenIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpenIncidentsRequest.ProtoReflect.Descriptor instead.
func (*UpdateOpenIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOpenIncidentsRequest) GetChopsService() *ChopsService {
	if x != nil {
		return x.ChopsService
	}
	return nil
}

type UpdateOpenIncidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenIncidents []*ChopsIncident       `protobuf:"bytes,1,rep,name=open_incidents,json=openIncidents,proto3" json:"open_incidents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOpenIncidentsResponse) Reset() {
	*x = UpdateOpenIncidentsResponse{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOpenIncidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpenIncidentsResponse) ProtoMessage() {}

func (x *UpdateOpenIncidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpenIncidentsResponse.ProtoReflect.Descriptor instead.
func (*UpdateOpenIncidentsResponse) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOpenIncidentsResponse) GetOpenIncidents() []*ChopsIncident {
	if x != nil {
		return x.OpenIncidents
	}
	return nil
}

type GetAllServicesDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unix timestamp to indicate the upper limit of the seven-day query range.
	// A value of 0 indicates interest in incidents that occurred in the last 7 days.
	UptoTime      int64 `protobuf:"varint,1,opt,name=upto_time,json=uptoTime,proto3" json:"upto_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllServicesDataRequest) Reset() {
	*x = GetAllServicesDataRequest{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllServicesDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllServicesDataRequest) ProtoMessage() {}

func (x *GetAllServicesDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllServicesDataRequest.ProtoReflect.Descriptor instead.
func (*GetAllServicesDataRequest) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllServicesDataRequest) GetUptoTime() int64 {
	if x != nil {
		return x.UptoTime
	}
	return 0
}

type GetAllServicesDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Services       []*ChopsService        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	NonslaServices []*ChopsService        `protobuf:"bytes,2,rep,name=nonsla_services,json=nonslaServices,proto3" json:"nonsla_services,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllServicesDataResponse) Reset() {
	*x = GetAllServicesDataResponse{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllServicesDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllServicesDataResponse) ProtoMessage() {}

func (x *GetAllServicesDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllServicesDataResponse.ProtoReflect.Descriptor instead.
func (*GetAllServicesDataResponse) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllServicesDataResponse) GetServices() []*ChopsService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetAllServicesDataResponse) GetNonslaServices() []*ChopsService {
	if x != nil {
		return x.NonslaServices
	}
	return nil
}

type ChopsIncident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Open          bool                   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Severity      Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=dashboard.Severity" json:"severity,omitempty"`
	IncidentLink  string                 `protobuf:"bytes,6,opt,name=incident_link,json=incidentLink,proto3" json:"incident_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChopsIncident) Reset() {
	*x = ChopsIncident{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChopsIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChopsIncident) ProtoMessage() {}

func (x *ChopsIncident) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChopsIncident.ProtoReflect.Descriptor instead.
func (*ChopsIncident) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *ChopsIncident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChopsIncident) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *ChopsIncident) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ChopsIncident) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ChopsIncident) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_UNDEFINED
}

func (x *ChopsIncident) GetIncidentLink() string {
	if x != nil {
		return x.IncidentLink
	}
	return ""
}

type ChopsService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Incidents     []*ChopsIncident       `protobuf:"bytes,2,rep,name=incidents,proto3" json:"incidents,omitempty"`
	Sla           string                 `protobuf:"bytes,3,opt,name=sla,proto3" json:"sla,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChopsService) Reset() {
	*x = ChopsService{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChopsService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChopsService) ProtoMessage() {}

func (x *ChopsService) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChopsService.ProtoReflect.Descriptor instead.
func (*ChopsService) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *ChopsService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChopsService) GetIncidents() []*ChopsIncident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

func (x *ChopsService) GetSla() string {
	if x != nil {
		return x.Sla
	}
	return ""
}

type CreateLiveAnnouncementRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageContent string                 `protobuf:"bytes,1,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	Platforms      []*Platform            `protobuf:"bytes,2,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLiveAnnouncementRequest) Reset() {
	*x = CreateLiveAnnouncementRequest{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiveAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveAnnouncementRequest) ProtoMessage() {}

func (x *CreateLiveAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*CreateLiveAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLiveAnnouncementRequest) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *CreateLiveAnnouncementRequest) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type CreateLiveAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcement  *Announcement          `protobuf:"bytes,1,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLiveAnnouncementResponse) Reset() {
	*x = CreateLiveAnnouncementResponse{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiveAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveAnnouncementResponse) ProtoMessage() {}

func (x *CreateLiveAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*CreateLiveAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLiveAnnouncementResponse) GetAnnouncement() *Announcement {
	if x != nil {
		return x.Announcement
	}
	return nil
}

type RetireAnnouncementRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnouncementId int64                  `protobuf:"varint,1,opt,name=announcement_id,json=announcementId,proto3" json:"announcement_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetireAnnouncementRequest) Reset() {
	*x = RetireAnnouncementRequest{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetireAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireAnnouncementRequest) ProtoMessage() {}

func (x *RetireAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*RetireAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *RetireAnnouncementRequest) GetAnnouncementId() int64 {
	if x != nil {
		return x.AnnouncementId
	}
	return 0
}

type SearchAnnouncementsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PlatformName string                 `protobuf:"bytes,1,opt,name=platform_name,json=platformName,proto3" json:"platform_name,omitempty"`
	Retired      bool                   `protobuf:"varint,2,opt,name=retired,proto3" json:"retired,omitempty"`
	// A limit <= 0 will be ignored.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// An offset < 0, will be ignored.
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAnnouncementsRequest) Reset() {
	*x = SearchAnnouncementsRequest{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnnouncementsRequest) ProtoMessage() {}

func (x *SearchAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*SearchAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *SearchAnnouncementsRequest) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *SearchAnnouncementsRequest) GetRetired() bool {
	if x != nil {
		return x.Retired
	}
	return false
}

func (x *SearchAnnouncementsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchAnnouncementsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchAnnouncementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcements []*Announcement        `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAnnouncementsResponse) Reset() {
	*x = SearchAnnouncementsResponse{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnnouncementsResponse) ProtoMessage() {}

func (x *SearchAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*SearchAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *SearchAnnouncementsResponse) GetAnnouncements() []*Announcement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

// Platform represents a ChOps frontend service (eg. "monorail", "gerrit" for chromium) in
// which Announcement messages should be displayed.
type Platform struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Specific pages in which the Announcement should be shown.
	// If no url_paths are given, the Announcement should
	// be visible on every page of the service.
	UrlPaths      []string `protobuf:"bytes,2,rep,name=url_paths,json=urlPaths,proto3" json:"url_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *Platform) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Platform) GetUrlPaths() []string {
	if x != nil {
		return x.UrlPaths
	}
	return nil
}

type Announcement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	MessageContent string                 `protobuf:"bytes,3,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	Creator        string                 `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Announcements that are retired are no longer relevant to users
	// and should not be displayed in platforms.
	Retired   bool        `protobuf:"varint,6,opt,name=retired,proto3" json:"retired,omitempty"`
	Platforms []*Platform `protobuf:"bytes,7,rep,name=platforms,proto3" json:"platforms,omitempty"`
	// The user who retires the announcement.
	Closer        string `protobuf:"bytes,8,opt,name=closer,proto3" json:"closer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *Announcement) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Announcement) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Announcement) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *Announcement) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Announcement) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Announcement) GetRetired() bool {
	if x != nil {
		return x.Retired
	}
	return false
}

func (x *Announcement) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *Announcement) GetCloser() string {
	if x != nil {
		return x.Closer
	}
	return ""
}

var File_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto protoreflect.FileDescriptor

var file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDesc = string([]byte{
	0x0a, 0x47, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x70, 0x65, 0x6e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x68, 0x6f, 0x70, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x73,
	0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x6f, 0x70, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x0c, 0x63, 0x68, 0x6f, 0x70, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x5e, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x6f, 0x70, 0x73, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x38, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x70, 0x74, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x75, 0x70, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64,
	0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x6f, 0x70, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x40, 0x0a, 0x0f, 0x6e, 0x6f, 0x6e, 0x73, 0x6c, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x6f, 0x70, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x0e, 0x6e, 0x6f, 0x6e, 0x73, 0x6c, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x22, 0xc3, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x6f, 0x70, 0x73, 0x49, 0x6e, 0x63, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x63, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x6c, 0x0a, 0x0c, 0x43, 0x68, 0x6f, 0x70, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x69,
	0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x6f, 0x70, 0x73,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6c, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x6c, 0x61, 0x22, 0x7b, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x76, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x31, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x73, 0x22, 0x5d, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x73,
	0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0c, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x44, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x69, 0x72, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x1a, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x69, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0x5c, 0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x73, 0x68,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x3b, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x72, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x75, 0x72, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x73, 0x22, 0xb8,
	0x02, 0x0a, 0x0c, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x35, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x69, 0x72, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x74, 0x69, 0x72, 0x65, 0x64, 0x12, 0x31,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x72, 0x2a, 0x2e, 0x0a, 0x08, 0x53, 0x65, 0x76,
	0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x59, 0x45, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x32, 0xe1, 0x01, 0x0a, 0x12, 0x43, 0x68,
	0x6f, 0x70, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x66, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xc4, 0x02,
	0x0a, 0x12, 0x43, 0x68, 0x6f, 0x70, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x6f, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x76, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x76, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x69, 0x72, 0x65, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x74, 0x69, 0x72, 0x65, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x13,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x61, 0x73,
	0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d,
	0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x61, 0x70,
	0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescOnce sync.Once
	file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescData []byte
)

func file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescGZIP() []byte {
	file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescOnce.Do(func() {
		file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDesc), len(file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDesc)))
	})
	return file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDescData
}

var file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_goTypes = []any{
	(Severity)(0),                          // 0: dashboard.Severity
	(*UpdateOpenIncidentsRequest)(nil),     // 1: dashboard.UpdateOpenIncidentsRequest
	(*UpdateOpenIncidentsResponse)(nil),    // 2: dashboard.UpdateOpenIncidentsResponse
	(*GetAllServicesDataRequest)(nil),      // 3: dashboard.GetAllServicesDataRequest
	(*GetAllServicesDataResponse)(nil),     // 4: dashboard.GetAllServicesDataResponse
	(*ChopsIncident)(nil),                  // 5: dashboard.ChopsIncident
	(*ChopsService)(nil),                   // 6: dashboard.ChopsService
	(*CreateLiveAnnouncementRequest)(nil),  // 7: dashboard.CreateLiveAnnouncementRequest
	(*CreateLiveAnnouncementResponse)(nil), // 8: dashboard.CreateLiveAnnouncementResponse
	(*RetireAnnouncementRequest)(nil),      // 9: dashboard.RetireAnnouncementRequest
	(*SearchAnnouncementsRequest)(nil),     // 10: dashboard.SearchAnnouncementsRequest
	(*SearchAnnouncementsResponse)(nil),    // 11: dashboard.SearchAnnouncementsResponse
	(*Platform)(nil),                       // 12: dashboard.Platform
	(*Announcement)(nil),                   // 13: dashboard.Announcement
	(*timestamppb.Timestamp)(nil),          // 14: google.protobuf.Timestamp
}
var file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_depIdxs = []int32{
	6,  // 0: dashboard.UpdateOpenIncidentsRequest.chops_service:type_name -> dashboard.ChopsService
	5,  // 1: dashboard.UpdateOpenIncidentsResponse.open_incidents:type_name -> dashboard.ChopsIncident
	6,  // 2: dashboard.GetAllServicesDataResponse.services:type_name -> dashboard.ChopsService
	6,  // 3: dashboard.GetAllServicesDataResponse.nonsla_services:type_name -> dashboard.ChopsService
	0,  // 4: dashboard.ChopsIncident.severity:type_name -> dashboard.Severity
	5,  // 5: dashboard.ChopsService.incidents:type_name -> dashboard.ChopsIncident
	12, // 6: dashboard.CreateLiveAnnouncementRequest.platforms:type_name -> dashboard.Platform
	13, // 7: dashboard.CreateLiveAnnouncementResponse.announcement:type_name -> dashboard.Announcement
	13, // 8: dashboard.SearchAnnouncementsResponse.announcements:type_name -> dashboard.Announcement
	14, // 9: dashboard.Announcement.start_time:type_name -> google.protobuf.Timestamp
	14, // 10: dashboard.Announcement.end_time:type_name -> google.protobuf.Timestamp
	12, // 11: dashboard.Announcement.platforms:type_name -> dashboard.Platform
	1,  // 12: dashboard.ChopsServiceStatus.UpdateOpenIncidents:input_type -> dashboard.UpdateOpenIncidentsRequest
	3,  // 13: dashboard.ChopsServiceStatus.GetAllServicesData:input_type -> dashboard.GetAllServicesDataRequest
	7,  // 14: dashboard.ChopsAnnouncements.CreateLiveAnnouncement:input_type -> dashboard.CreateLiveAnnouncementRequest
	9,  // 15: dashboard.ChopsAnnouncements.RetireAnnouncement:input_type -> dashboard.RetireAnnouncementRequest
	10, // 16: dashboard.ChopsAnnouncements.SearchAnnouncements:input_type -> dashboard.SearchAnnouncementsRequest
	2,  // 17: dashboard.ChopsServiceStatus.UpdateOpenIncidents:output_type -> dashboard.UpdateOpenIncidentsResponse
	4,  // 18: dashboard.ChopsServiceStatus.GetAllServicesData:output_type -> dashboard.GetAllServicesDataResponse
	8,  // 19: dashboard.ChopsAnnouncements.CreateLiveAnnouncement:output_type -> dashboard.CreateLiveAnnouncementResponse
	13, // 20: dashboard.ChopsAnnouncements.RetireAnnouncement:output_type -> dashboard.Announcement
	11, // 21: dashboard.ChopsAnnouncements.SearchAnnouncements:output_type -> dashboard.SearchAnnouncementsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_init() }
func file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_init() {
	if File_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDesc), len(file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_goTypes,
		DependencyIndexes: file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_depIdxs,
		EnumInfos:         file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_enumTypes,
		MessageInfos:      file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_msgTypes,
	}.Build()
	File_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto = out.File
	file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_goTypes = nil
	file_go_chromium_org_infra_appengine_dashboard_api_dashboard_dashboard_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChopsServiceStatusClient is the client API for ChopsServiceStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChopsServiceStatusClient interface {
	UpdateOpenIncidents(ctx context.Context, in *UpdateOpenIncidentsRequest, opts ...grpc.CallOption) (*UpdateOpenIncidentsResponse, error)
	GetAllServicesData(ctx context.Context, in *GetAllServicesDataRequest, opts ...grpc.CallOption) (*GetAllServicesDataResponse, error)
}
type chopsServiceStatusPRPCClient struct {
	client *prpc.Client
}

func NewChopsServiceStatusPRPCClient(client *prpc.Client) ChopsServiceStatusClient {
	return &chopsServiceStatusPRPCClient{client}
}

func (c *chopsServiceStatusPRPCClient) UpdateOpenIncidents(ctx context.Context, in *UpdateOpenIncidentsRequest, opts ...grpc.CallOption) (*UpdateOpenIncidentsResponse, error) {
	out := new(UpdateOpenIncidentsResponse)
	err := c.client.Call(ctx, "dashboard.ChopsServiceStatus", "UpdateOpenIncidents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chopsServiceStatusPRPCClient) GetAllServicesData(ctx context.Context, in *GetAllServicesDataRequest, opts ...grpc.CallOption) (*GetAllServicesDataResponse, error) {
	out := new(GetAllServicesDataResponse)
	err := c.client.Call(ctx, "dashboard.ChopsServiceStatus", "GetAllServicesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type chopsServiceStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewChopsServiceStatusClient(cc grpc.ClientConnInterface) ChopsServiceStatusClient {
	return &chopsServiceStatusClient{cc}
}

func (c *chopsServiceStatusClient) UpdateOpenIncidents(ctx context.Context, in *UpdateOpenIncidentsRequest, opts ...grpc.CallOption) (*UpdateOpenIncidentsResponse, error) {
	out := new(UpdateOpenIncidentsResponse)
	err := c.cc.Invoke(ctx, "/dashboard.ChopsServiceStatus/UpdateOpenIncidents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chopsServiceStatusClient) GetAllServicesData(ctx context.Context, in *GetAllServicesDataRequest, opts ...grpc.CallOption) (*GetAllServicesDataResponse, error) {
	out := new(GetAllServicesDataResponse)
	err := c.cc.Invoke(ctx, "/dashboard.ChopsServiceStatus/GetAllServicesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChopsServiceStatusServer is the server API for ChopsServiceStatus service.
type ChopsServiceStatusServer interface {
	UpdateOpenIncidents(context.Context, *UpdateOpenIncidentsRequest) (*UpdateOpenIncidentsResponse, error)
	GetAllServicesData(context.Context, *GetAllServicesDataRequest) (*GetAllServicesDataResponse, error)
}

// UnimplementedChopsServiceStatusServer can be embedded to have forward compatible implementations.
type UnimplementedChopsServiceStatusServer struct {
}

func (*UnimplementedChopsServiceStatusServer) UpdateOpenIncidents(context.Context, *UpdateOpenIncidentsRequest) (*UpdateOpenIncidentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOpenIncidents not implemented")
}
func (*UnimplementedChopsServiceStatusServer) GetAllServicesData(context.Context, *GetAllServicesDataRequest) (*GetAllServicesDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllServicesData not implemented")
}

func RegisterChopsServiceStatusServer(s prpc.Registrar, srv ChopsServiceStatusServer) {
	s.RegisterService(&_ChopsServiceStatus_serviceDesc, srv)
}

func _ChopsServiceStatus_UpdateOpenIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOpenIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChopsServiceStatusServer).UpdateOpenIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.ChopsServiceStatus/UpdateOpenIncidents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChopsServiceStatusServer).UpdateOpenIncidents(ctx, req.(*UpdateOpenIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChopsServiceStatus_GetAllServicesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllServicesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChopsServiceStatusServer).GetAllServicesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.ChopsServiceStatus/GetAllServicesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChopsServiceStatusServer).GetAllServicesData(ctx, req.(*GetAllServicesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChopsServiceStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.ChopsServiceStatus",
	HandlerType: (*ChopsServiceStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateOpenIncidents",
			Handler:    _ChopsServiceStatus_UpdateOpenIncidents_Handler,
		},
		{
			MethodName: "GetAllServicesData",
			Handler:    _ChopsServiceStatus_GetAllServicesData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.chromium.org/infra/appengine/dashboard/api/dashboard/dashboard.proto",
}

// ChopsAnnouncementsClient is the client API for ChopsAnnouncements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChopsAnnouncementsClient interface {
	CreateLiveAnnouncement(ctx context.Context, in *CreateLiveAnnouncementRequest, opts ...grpc.CallOption) (*CreateLiveAnnouncementResponse, error)
	RetireAnnouncement(ctx context.Context, in *RetireAnnouncementRequest, opts ...grpc.CallOption) (*Announcement, error)
	SearchAnnouncements(ctx context.Context, in *SearchAnnouncementsRequest, opts ...grpc.CallOption) (*SearchAnnouncementsResponse, error)
}
type chopsAnnouncementsPRPCClient struct {
	client *prpc.Client
}

func NewChopsAnnouncementsPRPCClient(client *prpc.Client) ChopsAnnouncementsClient {
	return &chopsAnnouncementsPRPCClient{client}
}

func (c *chopsAnnouncementsPRPCClient) CreateLiveAnnouncement(ctx context.Context, in *CreateLiveAnnouncementRequest, opts ...grpc.CallOption) (*CreateLiveAnnouncementResponse, error) {
	out := new(CreateLiveAnnouncementResponse)
	err := c.client.Call(ctx, "dashboard.ChopsAnnouncements", "CreateLiveAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chopsAnnouncementsPRPCClient) RetireAnnouncement(ctx context.Context, in *RetireAnnouncementRequest, opts ...grpc.CallOption) (*Announcement, error) {
	out := new(Announcement)
	err := c.client.Call(ctx, "dashboard.ChopsAnnouncements", "RetireAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chopsAnnouncementsPRPCClient) SearchAnnouncements(ctx context.Context, in *SearchAnnouncementsRequest, opts ...grpc.CallOption) (*SearchAnnouncementsResponse, error) {
	out := new(SearchAnnouncementsResponse)
	err := c.client.Call(ctx, "dashboard.ChopsAnnouncements", "SearchAnnouncements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type chopsAnnouncementsClient struct {
	cc grpc.ClientConnInterface
}

func NewChopsAnnouncementsClient(cc grpc.ClientConnInterface) ChopsAnnouncementsClient {
	return &chopsAnnouncementsClient{cc}
}

func (c *chopsAnnouncementsClient) CreateLiveAnnouncement(ctx context.Context, in *CreateLiveAnnouncementRequest, opts ...grpc.CallOption) (*CreateLiveAnnouncementResponse, error) {
	out := new(CreateLiveAnnouncementResponse)
	err := c.cc.Invoke(ctx, "/dashboard.ChopsAnnouncements/CreateLiveAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chopsAnnouncementsClient) RetireAnnouncement(ctx context.Context, in *RetireAnnouncementRequest, opts ...grpc.CallOption) (*Announcement, error) {
	out := new(Announcement)
	err := c.cc.Invoke(ctx, "/dashboard.ChopsAnnouncements/RetireAnnouncement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chopsAnnouncementsClient) SearchAnnouncements(ctx context.Context, in *SearchAnnouncementsRequest, opts ...grpc.CallOption) (*SearchAnnouncementsResponse, error) {
	out := new(SearchAnnouncementsResponse)
	err := c.cc.Invoke(ctx, "/dashboard.ChopsAnnouncements/SearchAnnouncements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChopsAnnouncementsServer is the server API for ChopsAnnouncements service.
type ChopsAnnouncementsServer interface {
	CreateLiveAnnouncement(context.Context, *CreateLiveAnnouncementRequest) (*CreateLiveAnnouncementResponse, error)
	RetireAnnouncement(context.Context, *RetireAnnouncementRequest) (*Announcement, error)
	SearchAnnouncements(context.Context, *SearchAnnouncementsRequest) (*SearchAnnouncementsResponse, error)
}

// UnimplementedChopsAnnouncementsServer can be embedded to have forward compatible implementations.
type UnimplementedChopsAnnouncementsServer struct {
}

func (*UnimplementedChopsAnnouncementsServer) CreateLiveAnnouncement(context.Context, *CreateLiveAnnouncementRequest) (*CreateLiveAnnouncementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLiveAnnouncement not implemented")
}
func (*UnimplementedChopsAnnouncementsServer) RetireAnnouncement(context.Context, *RetireAnnouncementRequest) (*Announcement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetireAnnouncement not implemented")
}
func (*UnimplementedChopsAnnouncementsServer) SearchAnnouncements(context.Context, *SearchAnnouncementsRequest) (*SearchAnnouncementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAnnouncements not implemented")
}

func RegisterChopsAnnouncementsServer(s prpc.Registrar, srv ChopsAnnouncementsServer) {
	s.RegisterService(&_ChopsAnnouncements_serviceDesc, srv)
}

func _ChopsAnnouncements_CreateLiveAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLiveAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChopsAnnouncementsServer).CreateLiveAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.ChopsAnnouncements/CreateLiveAnnouncement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChopsAnnouncementsServer).CreateLiveAnnouncement(ctx, req.(*CreateLiveAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChopsAnnouncements_RetireAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChopsAnnouncementsServer).RetireAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.ChopsAnnouncements/RetireAnnouncement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChopsAnnouncementsServer).RetireAnnouncement(ctx, req.(*RetireAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChopsAnnouncements_SearchAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAnnouncementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChopsAnnouncementsServer).SearchAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.ChopsAnnouncements/SearchAnnouncements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChopsAnnouncementsServer).SearchAnnouncements(ctx, req.(*SearchAnnouncementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChopsAnnouncements_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.ChopsAnnouncements",
	HandlerType: (*ChopsAnnouncementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLiveAnnouncement",
			Handler:    _ChopsAnnouncements_CreateLiveAnnouncement_Handler,
		},
		{
			MethodName: "RetireAnnouncement",
			Handler:    _ChopsAnnouncements_RetireAnnouncement_Handler,
		},
		{
			MethodName: "SearchAnnouncements",
			Handler:    _ChopsAnnouncements_SearchAnnouncements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.chromium.org/infra/appengine/dashboard/api/dashboard/dashboard.proto",
}
