// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package fleetcost.api.models;

import "go.chromium.org/infra/cros/fleetcost/api/models/cost_report.proto";

option go_package = "go.chromium.org/infra/cros/fleetcost/api/models;fleetcostpb";

// CostResult is a breakdown of cost for a given device.
message CostResult {
    // Dedicated cost is the cost for just this device.
    double dedicated_cost = 1;
    // Shared cost is the pro-rated share of fixed costs.
    double shared_cost = 2;
    // Cloud service cost is the pro-rated share of cloud-service-related costs for the device in question.
    double cloud_service_cost = 3;

    // CostReport is an output-only field
    fleetcost.api.models.CostReport report = 4;
}
