// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package unifiedfleet.api.v1.models.chromeos.lab;

option go_package = "go.chromium.org/infra/unifiedfleet/api/v1/models/chromeos/lab;ufspb";

import "go.chromium.org/infra/unifiedfleet/api/v1/models/chromeos/lab/rpm.proto";

// Major hardware revision for Dolos
// Next Tag: 2
enum DolosHWMajorRevision {
  // Default unset value
  DOLOS_UNSPECIFIED = 0;
  DOLOS_V1 = 1;
}

// Next Tag: 7
message Dolos {
  // Serial used to identify device over USB
  string serial_cable = 1;
  // Serial of the cable_cable
  string serial_usb = 2;
  // Hardware revision
  DolosHWMajorRevision hw_major_revision = 3;
  // Dolos firmware version
  string fw_version = 4;
  // Hostname of the host machine the dolos connected to via USB cable.
  string hostname = 5;
  // RPM that controls the power source for Dolos.
  OSRPM rpm = 6;
}
