// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.31.1
// source: go.chromium.org/infra/unifiedfleet/api/v1/models/chromeos/lab/pasit.proto

package ufspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of device represented.
type Pasit_Device_Type int32

const (
	Pasit_Device_UNKNOWN         Pasit_Device_Type = 0
	Pasit_Device_DUT             Pasit_Device_Type = 1
	Pasit_Device_SWITCH_FIXTURE  Pasit_Device_Type = 2
	Pasit_Device_DOCKING_STATION Pasit_Device_Type = 3
	Pasit_Device_MONITOR         Pasit_Device_Type = 4
	Pasit_Device_CAMERA          Pasit_Device_Type = 5
	Pasit_Device_STORAGE         Pasit_Device_Type = 6
	Pasit_Device_HID             Pasit_Device_Type = 7
	Pasit_Device_NETWORK         Pasit_Device_Type = 8
	Pasit_Device_HEADPHONE       Pasit_Device_Type = 9
	Pasit_Device_SPEAKER         Pasit_Device_Type = 10
	Pasit_Device_IP_POWER        Pasit_Device_Type = 11
)

// Enum value maps for Pasit_Device_Type.
var (
	Pasit_Device_Type_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "DUT",
		2:  "SWITCH_FIXTURE",
		3:  "DOCKING_STATION",
		4:  "MONITOR",
		5:  "CAMERA",
		6:  "STORAGE",
		7:  "HID",
		8:  "NETWORK",
		9:  "HEADPHONE",
		10: "SPEAKER",
		11: "IP_POWER",
	}
	Pasit_Device_Type_value = map[string]int32{
		"UNKNOWN":         0,
		"DUT":             1,
		"SWITCH_FIXTURE":  2,
		"DOCKING_STATION": 3,
		"MONITOR":         4,
		"CAMERA":          5,
		"STORAGE":         6,
		"HID":             7,
		"NETWORK":         8,
		"HEADPHONE":       9,
		"SPEAKER":         10,
		"IP_POWER":        11,
	}
)

func (x Pasit_Device_Type) Enum() *Pasit_Device_Type {
	p := new(Pasit_Device_Type)
	*p = x
	return p
}

func (x Pasit_Device_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pasit_Device_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_enumTypes[0].Descriptor()
}

func (Pasit_Device_Type) Type() protoreflect.EnumType {
	return &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_enumTypes[0]
}

func (x Pasit_Device_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pasit_Device_Type.Descriptor instead.
func (Pasit_Device_Type) EnumDescriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescGZIP(), []int{0, 1, 0}
}

// PASIT is a connected set of peripheral components used in interop testing.
// The components connected are controlled via an external host. Pasit
// describes the devices in the testbed and their connection topology.
type Pasit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the host that controls the devices (e.g. switches)
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The components/devices in the PASIT testbed (e.g. docks, switches, cameras,
	// monitors, etc)
	Devices []*Pasit_Device `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// The connections between devices/components in the testbed.
	Connections   []*Pasit_Connection `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pasit) Reset() {
	*x = Pasit{}
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pasit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pasit) ProtoMessage() {}

func (x *Pasit) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pasit.ProtoReflect.Descriptor instead.
func (*Pasit) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescGZIP(), []int{0}
}

func (x *Pasit) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Pasit) GetDevices() []*Pasit_Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *Pasit) GetConnections() []*Pasit_Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

// A single connection between two components in the topology.
type Pasit_Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the parent device has multiple connection ports/slots,
	// this is the name or id of the port.
	ParentPort string `protobuf:"bytes,1,opt,name=parent_port,json=parentPort,proto3" json:"parent_port,omitempty"`
	// The ID of the parent component;
	ParentId string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// The ID of the child component;
	ChildId string `protobuf:"bytes,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	// The speed of the connection.
	Speed float32 `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	// The physical port type/technology, e.g. "USBA", "USBC", "HDMI".
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// Tags associated with the connection, e.g. "DOCK", "DOCKLESS", "DAISY_CHAIN" see go/pasit-multi-topology.
	Tags          []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pasit_Connection) Reset() {
	*x = Pasit_Connection{}
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pasit_Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pasit_Connection) ProtoMessage() {}

func (x *Pasit_Connection) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pasit_Connection.ProtoReflect.Descriptor instead.
func (*Pasit_Connection) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Pasit_Connection) GetParentPort() string {
	if x != nil {
		return x.ParentPort
	}
	return ""
}

func (x *Pasit_Connection) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Pasit_Connection) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *Pasit_Connection) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Pasit_Connection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Pasit_Connection) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// A single device/component in the testbed.
type Pasit_Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the device. This is not unique across all devices,
	// in the lab but is unique within a testbed.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The the make/model of the device.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// The type of device represented.
	Type Pasit_Device_Type `protobuf:"varint,3,opt,name=type,proto3,enum=unifiedfleet.api.v1.models.chromeos.lab.Pasit_Device_Type" json:"type,omitempty"`
	// Additional power supply information for devices that provide
	// power to the DUT.
	PowerSupply *Pasit_Device_PowerSupply `protobuf:"bytes,4,opt,name=power_supply,json=powerSupply,proto3" json:"power_supply,omitempty"`
	// Optional RPM if one exists
	Rpm           *OSRPM `protobuf:"bytes,5,opt,name=rpm,proto3" json:"rpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pasit_Device) Reset() {
	*x = Pasit_Device{}
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pasit_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pasit_Device) ProtoMessage() {}

func (x *Pasit_Device) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pasit_Device.ProtoReflect.Descriptor instead.
func (*Pasit_Device) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Pasit_Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pasit_Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Pasit_Device) GetType() Pasit_Device_Type {
	if x != nil {
		return x.Type
	}
	return Pasit_Device_UNKNOWN
}

func (x *Pasit_Device) GetPowerSupply() *Pasit_Device_PowerSupply {
	if x != nil {
		return x.PowerSupply
	}
	return nil
}

func (x *Pasit_Device) GetRpm() *OSRPM {
	if x != nil {
		return x.Rpm
	}
	return nil
}

// Information on the power capabilities of the device.
type Pasit_Device_PowerSupply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       float32                `protobuf:"fixed32,1,opt,name=current,proto3" json:"current,omitempty"`
	Voltage       float32                `protobuf:"fixed32,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Power         float32                `protobuf:"fixed32,3,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pasit_Device_PowerSupply) Reset() {
	*x = Pasit_Device_PowerSupply{}
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pasit_Device_PowerSupply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pasit_Device_PowerSupply) ProtoMessage() {}

func (x *Pasit_Device_PowerSupply) ProtoReflect() protoreflect.Message {
	mi := &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pasit_Device_PowerSupply.ProtoReflect.Descriptor instead.
func (*Pasit_Device_PowerSupply) Descriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Pasit_Device_PowerSupply) GetCurrent() float32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Pasit_Device_PowerSupply) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *Pasit_Device_PowerSupply) GetPower() float32 {
	if x != nil {
		return x.Power
	}
	return 0
}

var File_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto protoreflect.FileDescriptor

var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDesc = string([]byte{
	0x0a, 0x49, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f, 0x73, 0x2f, 0x6c, 0x61, 0x62, 0x2f,
	0x70, 0x61, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x75, 0x6e, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f, 0x73,
	0x2e, 0x6c, 0x61, 0x62, 0x1a, 0x47, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x75, 0x6e, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f, 0x73, 0x2f,
	0x6c, 0x61, 0x62, 0x2f, 0x72, 0x70, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x07,
	0x0a, 0x05, 0x50, 0x61, 0x73, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x4f, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f, 0x73, 0x2e, 0x6c, 0x61, 0x62, 0x2e, 0x50,
	0x61, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x5b, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x75, 0x6e, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f, 0x73, 0x2e,
	0x6c, 0x61, 0x62, 0x2e, 0x50, 0x61, 0x73, 0x69, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0xa3, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0xad, 0x04, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x4e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f, 0x73, 0x2e, 0x6c, 0x61, 0x62,
	0x2e, 0x50, 0x61, 0x73, 0x69, 0x74, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x64, 0x0a, 0x0c, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41,
	0x2e, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x65, 0x6f, 0x73, 0x2e, 0x6c, 0x61, 0x62, 0x2e, 0x50, 0x61, 0x73, 0x69, 0x74, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x40,
	0x0a, 0x03, 0x72, 0x70, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x75, 0x6e,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x6f,
	0x73, 0x2e, 0x6c, 0x61, 0x62, 0x2e, 0x4f, 0x53, 0x52, 0x50, 0x4d, 0x52, 0x03, 0x72, 0x70, 0x6d,
	0x1a, 0x57, 0x0a, 0x0b, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x6f, 0x6c,
	0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x76, 0x6f, 0x6c, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x22, 0xab, 0x01, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x44, 0x55, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x57, 0x49, 0x54,
	0x43, 0x48, 0x5f, 0x46, 0x49, 0x58, 0x54, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f,
	0x44, 0x4f, 0x43, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x4f, 0x4e, 0x49, 0x54, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54,
	0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x49, 0x44, 0x10, 0x07,
	0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x08, 0x12, 0x0d, 0x0a,
	0x09, 0x48, 0x45, 0x41, 0x44, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x50, 0x45, 0x41, 0x4b, 0x45, 0x52, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x50, 0x5f,
	0x50, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x0b, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x6f, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x2f, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x65, 0x6f, 0x73, 0x2f, 0x6c, 0x61, 0x62, 0x3b, 0x75, 0x66, 0x73, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescOnce sync.Once
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescData []byte
)

func file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescGZIP() []byte {
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescOnce.Do(func() {
		file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDesc), len(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDesc)))
	})
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDescData
}

var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_goTypes = []any{
	(Pasit_Device_Type)(0),           // 0: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.Type
	(*Pasit)(nil),                    // 1: unifiedfleet.api.v1.models.chromeos.lab.Pasit
	(*Pasit_Connection)(nil),         // 2: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Connection
	(*Pasit_Device)(nil),             // 3: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device
	(*Pasit_Device_PowerSupply)(nil), // 4: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.PowerSupply
	(*OSRPM)(nil),                    // 5: unifiedfleet.api.v1.models.chromeos.lab.OSRPM
}
var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_depIdxs = []int32{
	3, // 0: unifiedfleet.api.v1.models.chromeos.lab.Pasit.devices:type_name -> unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device
	2, // 1: unifiedfleet.api.v1.models.chromeos.lab.Pasit.connections:type_name -> unifiedfleet.api.v1.models.chromeos.lab.Pasit.Connection
	0, // 2: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.type:type_name -> unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.Type
	4, // 3: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.power_supply:type_name -> unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.PowerSupply
	5, // 4: unifiedfleet.api.v1.models.chromeos.lab.Pasit.Device.rpm:type_name -> unifiedfleet.api.v1.models.chromeos.lab.OSRPM
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_init() }
func file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_init() {
	if File_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto != nil {
		return
	}
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_rpm_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDesc), len(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_goTypes,
		DependencyIndexes: file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_depIdxs,
		EnumInfos:         file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_enumTypes,
		MessageInfos:      file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_msgTypes,
	}.Build()
	File_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto = out.File
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_goTypes = nil
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chromeos_lab_pasit_proto_depIdxs = nil
}
