// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package unifiedfleet.api.v1.models.chromeos.lab;

option go_package = "go.chromium.org/infra/unifiedfleet/api/v1/models/chromeos/lab;ufspb";

// This proto defines sim labels in lab config of a DUT.

// Next Tag: 6
message SIMInfo {
  int32 slot_id = 1;
  SIMType type = 2;
  string eid = 3;
  bool test_esim = 4;
  repeated SIMProfileInfo profile_info = 5;
}

// Next Tag: 7
message SIMProfileInfo {
  string iccid = 1;
  string sim_pin = 2;
  string sim_puk = 3;
  NetworkProvider carrier_name = 4;
  string own_number = 5;
  // The SIM state as reported by the cellular modem.
  State state = 6;

  // Possible states of the SIM profile.
  enum State {
    // State not set.
    UNSPECIFIED = 0;
    // The device is unusable.
    BROKEN = 1;
    // The device needs to be unlocked.
    LOCKED = 2;
    // No data connection available and not in a failed state.
    NO_NETWORK = 3;
    // The device is registered with a network provider, and data connections and messaging may be available for use.
    WORKING = 4;
    // The device has an invalid configuration in UFS.
    WRONG_CONFIG = 5;
  }

  // Features supported by the profile.
  // These features are used to determine what tests can be run against which SIMs
  // in the lab, see go/cros-cellular-features for more information.
  // File bugs against buganizer component: 979102.
  repeated Feature features = 7;

  // Possible features that the SIM supports.
  enum Feature {
    // Unset feature.
    FEATURE_UNSPECIFIED = 0;
    // The SIM supports a generic live network.
    FEATURE_LIVE_NETWORK = 1;
    // The SIM supports SMS messaging.
    FEATURE_SMS = 2;
  }
}

// Next Tag: 22
enum NetworkProvider {
  NETWORK_OTHER = 0;
  NETWORK_UNSUPPORTED = 5;
  NETWORK_TEST = 1;
  NETWORK_ATT = 2;
  NETWORK_TMOBILE = 3;
  NETWORK_VERIZON = 4;
  NETWORK_SPRINT = 6;
  NETWORK_DOCOMO = 7;
  NETWORK_SOFTBANK = 8;
  NETWORK_KDDI = 9;
  NETWORK_RAKUTEN = 10;
  NETWORK_VODAFONE = 11;
  NETWORK_EE = 12;
  NETWORK_AMARISOFT = 13;
  NETWORK_ROGER = 14;
  NETWORK_BELL = 15;
  NETWORK_TELUS = 16;
  NETWORK_FI = 17;
  NETWORK_CBRS = 18;
  NETWORK_LINEMO = 19;
  NETWORK_POVO = 20;
  NETWORK_HANSHIN = 21;
}

// Next Tag: 3
enum SIMType {
  SIM_UNKNOWN = 0;
  SIM_PHYSICAL = 1;
  SIM_DIGITAL = 2;
}
