// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package service

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"go.chromium.org/chromiumos/config/go/test/api"
)

const (
	// AL specific consts
	AL_PROJECT_PREFIX           = "al_project"
	AL_PACKAGE_TIMESTAMP_FORMAT = "2006.01.02_15.04.05.999"

	// The result files generated by tradefed
	XTS_RESULT_FILENAME            = "test_result.xml"
	XTS_RESULT_FILENAME_COMPRESSED = XTS_RESULT_FILENAME + ".tgz"

	// Autotest test to collect list of CTS tests
	TEST_LIST_COLLECTOR = "tradefed-run-collect-tests-only"
	TRY_BOT_PREFIX      = "trybot-"

	// Regex patterns
	DIGIT = `[0-9][0-9]`
)

var (
	// The regexp to extract build version from the build, e.g. brya-release/R133-16103.0.0
	BUILD_VERSION_REGEX = regexp.MustCompile(`.*/(.*)`)
	RELEASE_BUILD_REGEX = regexp.MustCompile(`.*-release/.*`)

	// Regex patterns
	TIMESTAMP_REGEX = fmt.Sprintf("%s%s.%s.%s_%s.%s.%s*", DIGIT, DIGIT, DIGIT, DIGIT, DIGIT, DIGIT, DIGIT)

	// AL release configurations that do not need to be archived and skipped.
	// Release configurations are in the format: <target_name>-<release>-<variant>
	// See: go/trunk-stable-release-configurations
	AL_SKIP_RELEASE_BUILD_REGEX = regexp.MustCompile(`\w+-(trunk_food|trunk_staging)-\w+/.*`)
)

// ArchiveInfo defines the properties of a XTS archive process.
type ArchiveInfo struct {
	// User friendly name to be displayed in the LUCI MILO UI.
	Name string

	// The full path to the local file to be uploaded to GCS.
	// e.g. /path/to/result/dir/cros-test/results/1234567890.zip
	Source string

	// The GCS path to upload the source file to.
	Destination string
}

// archiveInfo gets the XTS archive infos for the overall test run.
// It scans the result dir from metadata to find the relevant XML result files and prepares
// them for upload with a list of archive instructions.
func archiveInfo(resultDir string, metadata *api.XtsArchiverMetadata, now time.Time) ([]ArchiveInfo, error) {
	if !isReleaseBuild(metadata.GetBuild(), metadata.GetAlRun()) {
		log.Printf("Skipping the XTS archive process for non-release build: %s", metadata.GetBuild())
		return nil, nil
	}

	// Define the known XTS patterns to find result dir housing the test result XML file.
	resultPatterns := make(map[string][]string)
	if metadata.GetAlRun() {
		// For AL runs, the result file is directly under the result dir
		resultPatterns[resultDir] = []string{XTS_RESULT_FILENAME}
	} else {
		xtsPattern := filepath.Join(resultDir, "*", "cheets_?TS_*", "results", "*", TIMESTAMP_REGEX)
		resultPatterns[xtsPattern] = []string{XTS_RESULT_FILENAME, XTS_RESULT_FILENAME_COMPRESSED}
	}

	// Attempt matching each pattern for this run, getting archive info for each.
	var infos []ArchiveInfo
	for resultPattern, filenames := range resultPatterns {
		resultDirs, err := filepath.Glob(resultPattern)
		if err != nil {
			fmt.Println("Error finding test directories: ", err)
			continue
		}

		for _, resultDir := range resultDirs {
			resultDirInfo, err := os.Stat(resultDir)
			if err != nil {
				fmt.Println("Error getting file info:", err)
				continue
			}

			if !resultDirInfo.IsDir() {
				continue
			}

			archiveInfos, err := archiveInfoForTest(resultDir, filenames, metadata, now)
			if err != nil {
				return nil, err
			}

			infos = append(infos, archiveInfos...)
		}
	}

	return infos, nil
}

// archiveInfoForTest gets the list of XTS archive info for a test result file found under
// the <resultDir>/<resultFilename>.
func archiveInfoForTest(resultDir string, resultFilenames []string, metadata *api.XtsArchiverMetadata, now time.Time) ([]ArchiveInfo, error) {
	var infos []ArchiveInfo
	harness, packageName, timestamp, err := parseJobResultsFilePath(resultDir, metadata.GetAlRun(), now)
	if err != nil {
		return nil, err
	}

	filePrefix := fmt.Sprintf("%s/%s_%s", packageName, harness, timestamp)

	// Add APFE archive info, skipping collect-test packages and AL runs.
	// TODO: b/379711782 - Support APFE upload for AL runs if needed.
	if !metadata.GetAlRun() && !strings.Contains(packageName, TEST_LIST_COLLECTOR) {
		log.Printf("Fetching XTS APFE archive info for package: %s", packageName)
		apfeInfo, err := apfeInfo(resultDir, filePrefix, metadata)
		if err != nil {
			log.Printf("Failed to get APFE infos: %v", err)
		} else {
			infos = append(infos, apfeInfo...)
		}
	} else {
		log.Printf("Skipping XTS results upload to APFE gs:// bucket for package: %s", packageName)
	}

	// Add results archive info for each supported result filename
	for _, resultFilename := range resultFilenames {
		resultsInfos, err := resultsInfo(resultDir, resultFilename, filePrefix, metadata)
		if err != nil {
			log.Printf("Failed to get result infos: %v", err)
		} else {
			infos = append(infos, resultsInfos...)
		}

	}

	return infos, nil
}

// apfeInfo gets the list info for archiving results to APFE GCS bucket. It scans
// the local dir for zip file that has the same name as the resultDir and constructs
// the upload name based on filePrefix and metadata.
func apfeInfo(resultDir, filePrefix string, metadata *api.XtsArchiverMetadata) ([]ArchiveInfo, error) {
	// Extract the build version from the build, a success match would have size of 2, one
	// for the entire string and one for the capturing clause.
	buildMatch := BUILD_VERSION_REGEX.FindStringSubmatch(metadata.GetBuild())
	if len(buildMatch) != 2 {
		return nil, fmt.Errorf("failed to parse build string: %s", metadata.GetBuild())
	}

	buildFormat := fmt.Sprintf("%s-release/%s", metadata.GetProduct(), buildMatch[1])
	prefix := fmt.Sprintf("%s/%s/%s", buildFormat, metadata.GetParentSwarmingTaskId(), filePrefix)
	apfeGCSPath := fmt.Sprintf("%s/%s/", metadata.GetApfeGcsPrefix(), prefix)

	// Find all the zip files in the XTS result dir
	zipFiles, err := filepath.Glob(fmt.Sprintf("%s.zip", resultDir))
	if err != nil {
		return nil, err
	}

	infos := make([]ArchiveInfo, 0, len(zipFiles))
	for _, zipFile := range zipFiles {
		infos = append(infos, ArchiveInfo{
			Name:        "apfe:" + prefix,
			Source:      zipFile,
			Destination: apfeGCSPath,
		})
	}

	return infos, nil
}

// resultsInfo gets the list of info for archiving results to results GCS bucket. It scans
// the resultDir for files with resultFilename and converts them to .gz files prior to upload.
func resultsInfo(resultDir, resultFilename, filePrefix string, metadata *api.XtsArchiverMetadata) ([]ArchiveInfo, error) {
	resultFiles, err := filepath.Glob(filepath.Join(resultDir, resultFilename))
	if err != nil {
		return nil, err
	}

	infos := make([]ArchiveInfo, 0, len(resultFiles))
	for _, resultFile := range resultFiles {
		// Extract .xml file from tgz file
		if filepath.Ext(resultFile) == ".tgz" {
			xmlFilename := strings.TrimSuffix(filepath.Base(resultFile), ".tgz")
			err := extractXMLFromTGZ(resultDir, resultFile, xmlFilename)
			if err != nil {
				log.Println("Error extracting XML result file from tgz file:", err)
				continue
			}

			resultFile = filepath.Join(resultDir, xmlFilename)
		}

		resultFileGZ := resultFile + ".gz"
		err := gzipFile(resultFile, resultFileGZ)
		if err != nil {
			log.Println("Error gzipping file:", err)
			continue
		}

		resultGCSPath := fmt.Sprintf("%s/%s/", metadata.GetResultsGcsPrefix(), filePrefix)
		infos = append(infos, ArchiveInfo{
			Name:        "results:" + filePrefix,
			Source:      resultFileGZ,
			Destination: resultGCSPath,
		})
	}

	return infos, nil
}

// extractXMLFromTGZ extracts the xmlFilename from tgzFilepath in the resultDir.
func extractXMLFromTGZ(resultDir, tgzFilepath, xmlFilename string) error {
	file, err := os.Open(tgzFilepath)
	if err != nil {
		return fmt.Errorf("opening tgz file: %w", err)
	}
	defer file.Close()

	gzr, err := gzip.NewReader(file)
	if err != nil {
		return fmt.Errorf("creating gzip reader: %w", err)
	}
	defer gzr.Close()

	tr := tar.NewReader(gzr)
	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("reading tar header: %w", err)
		}

		if header.Name == xmlFilename {
			outFile, err := os.Create(filepath.Join(resultDir, header.Name))
			if err != nil {
				return fmt.Errorf("creating output file: %w", err)
			}
			defer outFile.Close()

			if _, err := io.Copy(outFile, tr); err != nil {
				return fmt.Errorf("extracting file: %w", err)
			}
			return nil
		}
	}

	return fmt.Errorf("XML file: %s not found in tgz file: %s", xmlFilename, tgzFilepath)
}

// gzipFile writes src file to dst gzip file.
func gzipFile(src, dst string) error {
	reader, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("opening source file: %w", err)
	}
	defer reader.Close()

	writer, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("creating destination file: %w", err)
	}
	defer writer.Close()

	archiver := gzip.NewWriter(writer)
	defer archiver.Close()

	if _, err := io.Copy(archiver, reader); err != nil {
		return fmt.Errorf("running gzip on file: %w", err)
	}

	return nil
}

// parseJobResultsFilePath parses the path to extract test harness, package and timestamp information
// for the job. Currently only tauto (ChromeOS) and tradefed (AL) paths are supported.
//
//   - Tauto paths at least contain 6 dirs, e.g.:
//     /cros-test/results/tauto/results-1-cheets_GTS_12.internal.all.WvtsDeviceTestCases/
//     cheets_GTS_12.internal.all.WvtsDeviceTestCases/results/android-gts/2024.11.17_15.15.51.364_5161
//
//   - Tradefed paths at least contain 2 dirs with a max depth of 3, e.g.:
//     /cros-test/results/tradefed/
func parseJobResultsFilePath(path string, isALRun bool, now time.Time) (harness string, packageName string, timestamp string, err error) {
	folders := strings.Split(path, string(filepath.Separator))
	foldersLen := len(folders)

	// For AL project, the path does not identify the timestamp and package,
	// we will use the current timestamp to avoid upload conflict.
	if isALRun {
		if foldersLen < 2 {
			return "", "", "", fmt.Errorf("invalid tradefed path: %s", path)
		}
		return folders[foldersLen-1], AL_PROJECT_PREFIX, now.Format(AL_PACKAGE_TIMESTAMP_FORMAT), nil
	}

	if foldersLen < 6 {
		return "", "", "", fmt.Errorf("invalid tauto path: %s", path)
	}
	return folders[foldersLen-6], folders[foldersLen-4], folders[foldersLen-1], nil
}

// isReleaseBuild returns whether the build is for a release that needs to be archived.
func isReleaseBuild(build string, isALRun bool) bool {
	if isALRun {
		return !AL_SKIP_RELEASE_BUILD_REGEX.MatchString(build)
	}

	// ChromeOS classic build formats
	if strings.HasPrefix(build, TRY_BOT_PREFIX) {
		return false
	}
	return RELEASE_BUILD_REGEX.MatchString(build)
}

// validateXTSArchiverMetadata validates XTS archiver metadata.
func validateXTSArchiverMetadata(metadata *api.XtsArchiverMetadata) error {
	if metadata.GetBuild() == "" {
		return fmt.Errorf("build is required in metadata for XTS archiver")
	}

	if metadata.GetResultsGcsPrefix() == "" {
		return fmt.Errorf("results GCS prefix is required in metadata for XTS archiver")
	}

	if metadata.GetApfeGcsPrefix() == "" {
		return fmt.Errorf("APFE GCS prefix is required in metadata for XTS archiver")
	}

	return nil
}
