// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Copied from https://source.corp.google.com/piper///depot/google3/java/com/google/chrome/crosbuilds/common/proto/device.proto
// and edited
//TODO(b/297076502): Automate changes with Copybara

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.2
// source: go.chromium.org/infra/unifiedfleet/api/v1/models/chassis_x.proto

package ufspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChassisXBrandType int32

const (
	ChassisXBrandType_UNKNOWN ChassisXBrandType = 0
	// Deprecated: Marked as deprecated in go.chromium.org/infra/unifiedfleet/api/v1/models/chassis_x.proto.
	ChassisXBrandType_NO_BRAND ChassisXBrandType = 1
	// Deprecated: Marked as deprecated in go.chromium.org/infra/unifiedfleet/api/v1/models/chassis_x.proto.
	ChassisXBrandType_MIXED ChassisXBrandType = 2
	// Deprecated: Marked as deprecated in go.chromium.org/infra/unifiedfleet/api/v1/models/chassis_x.proto.
	ChassisXBrandType_ALL_BRANDED         ChassisXBrandType = 3
	ChassisXBrandType_NON_X               ChassisXBrandType = 4
	ChassisXBrandType_HARD_BRANDED        ChassisXBrandType = 5
	ChassisXBrandType_SOFT_BRANDED_LEGACY ChassisXBrandType = 6
	ChassisXBrandType_SOFT_BRANDED_WAIVER ChassisXBrandType = 7
	ChassisXBrandType_NA                  ChassisXBrandType = 8
)

// Enum value maps for ChassisXBrandType.
var (
	ChassisXBrandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NO_BRAND",
		2: "MIXED",
		3: "ALL_BRANDED",
		4: "NON_X",
		5: "HARD_BRANDED",
		6: "SOFT_BRANDED_LEGACY",
		7: "SOFT_BRANDED_WAIVER",
		8: "NA",
	}
	ChassisXBrandType_value = map[string]int32{
		"UNKNOWN":             0,
		"NO_BRAND":            1,
		"MIXED":               2,
		"ALL_BRANDED":         3,
		"NON_X":               4,
		"HARD_BRANDED":        5,
		"SOFT_BRANDED_LEGACY": 6,
		"SOFT_BRANDED_WAIVER": 7,
		"NA":                  8,
	}
)

func (x ChassisXBrandType) Enum() *ChassisXBrandType {
	p := new(ChassisXBrandType)
	*p = x
	return p
}

func (x ChassisXBrandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChassisXBrandType) Descriptor() protoreflect.EnumDescriptor {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_enumTypes[0].Descriptor()
}

func (ChassisXBrandType) Type() protoreflect.EnumType {
	return &file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_enumTypes[0]
}

func (x ChassisXBrandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChassisXBrandType.Descriptor instead.
func (ChassisXBrandType) EnumDescriptor() ([]byte, []int) {
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescGZIP(), []int{0}
}

var File_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto protoreflect.FileDescriptor

var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDesc = string([]byte{
	0x0a, 0x40, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x73, 0x73, 0x69, 0x73, 0x5f, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1a, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2a, 0xad,
	0x01, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x73, 0x73, 0x69, 0x73, 0x58, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44, 0x10, 0x01, 0x1a,
	0x02, 0x08, 0x01, 0x12, 0x0d, 0x0a, 0x05, 0x4d, 0x49, 0x58, 0x45, 0x44, 0x10, 0x02, 0x1a, 0x02,
	0x08, 0x01, 0x12, 0x13, 0x0a, 0x0b, 0x41, 0x4c, 0x4c, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44, 0x45,
	0x44, 0x10, 0x03, 0x1a, 0x02, 0x08, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x4e, 0x5f, 0x58,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x41, 0x52, 0x44, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44,
	0x45, 0x44, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x4f, 0x46, 0x54, 0x5f, 0x42, 0x52, 0x41,
	0x4e, 0x44, 0x45, 0x44, 0x5f, 0x4c, 0x45, 0x47, 0x41, 0x43, 0x59, 0x10, 0x06, 0x12, 0x17, 0x0a,
	0x13, 0x53, 0x4f, 0x46, 0x54, 0x5f, 0x42, 0x52, 0x41, 0x4e, 0x44, 0x45, 0x44, 0x5f, 0x57, 0x41,
	0x49, 0x56, 0x45, 0x52, 0x10, 0x07, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x41, 0x10, 0x08, 0x42, 0x38,
	0x5a, 0x36, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x3b, 0x75, 0x66, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescOnce sync.Once
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescData []byte
)

func file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescGZIP() []byte {
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescOnce.Do(func() {
		file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDesc), len(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDesc)))
	})
	return file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDescData
}

var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_goTypes = []any{
	(ChassisXBrandType)(0), // 0: unifiedfleet.api.v1.models.ChassisXBrandType
}
var file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_init() }
func file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_init() {
	if File_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDesc), len(file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_goTypes,
		DependencyIndexes: file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_depIdxs,
		EnumInfos:         file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_enumTypes,
	}.Build()
	File_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto = out.File
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_goTypes = nil
	file_go_chromium_org_infra_unifiedfleet_api_v1_models_chassis_x_proto_depIdxs = nil
}
