// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package unifiedfleet.api.v1.models;

option go_package = "go.chromium.org/infra/unifiedfleet/api/v1/models;ufspb";

// Next ID: 9
message OwnershipData {
   // resource group to which this bot belongs to - deprecated
   repeated string resource_group = 1 [deprecated=true];
   // security level of the bot ex:trusted, untrusted etc
   string security_level = 2;
   // security pool to which this bot belongs to - deprecated to support 
   // array of pools
   string pool_name = 3 [deprecated=true];
   // swarming instance to which this bot will communicate
   string swarming_instance = 4;
   // custom miba realm for this bot - deprecated
   string miba_realm = 5 [deprecated=true];
   // Customer who uses this bot.
   string customer = 6;
   // builders for this bot, if any
   repeated string builders = 7;
   // security pool(s) to which this bot belongs to
   repeated string pools = 8;
}
