# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/cros-registry/base-images/ubuntu:ubuntuProd
RUN apt-get update \
    && apt-get install -y curl

COPY rdb-publish /usr/bin/
COPY rdb /usr/bin/
COPY result_adapter /usr/bin/