# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/cros-registry/test-services/foil-provision:prod_base

COPY foil-provision /usr/bin/
# CLEAN(b/408454320): Remove once adb-logcat is containerized.
COPY adb-logcat /usr/bin/
