# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/chromeos-hw-tools/servod/servod:release
COPY cros-servod /usr/bin/
