# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM python:3.8-slim-buster AS build

RUN apt-get update && \
    apt-get install -y \
    wget

# Install python packages
# Due to the way builds happen in the bots, the requirements.txt has a
# different checksum (as the file path changes per build), thus breaks the
# cache. This way of declaring allows the cloudbuild cache to be carried
# between builds/boards.
# To update this list, add the new dep to requirements.in, regenerate the
# requirements_py3.txt, then manually copy in the dep to the list below,
# including the \n\.
RUN echo "\
chardet==3.0.4\n\
grpcio==1.31.0\n\
protobuf==3.18.0\n\
requests==2.26.0\n\
selenium==2.37.2\n\
six==1.15.0\n\
urllib3==1.26.7\n\
google.cloud\n\
google.cloud.pubsub\n\
google.cloud.storage\n\
" > requirements_py3.txt
RUN pip3 install -r requirements_py3.txt

COPY cpcon-publish /usr/bin/

RUN mkdir /usr/local/autotest
WORKDIR /usr/local/autotest

# Download autotest
RUN wget https://chromium.googlesource.com/chromiumos/third_party/autotest/+archive/refs/heads/main.tar.gz
RUN tar -xvzf main.tar.gz
RUN rm main.tar.gz

# Download tko_pb2.py
RUN wget https://chromium.googlesource.com/chromiumos/config/+archive/refs/heads/main/python/chromiumos/test/artifact.tar.gz
RUN tar -xvzf artifact.tar.gz -C tko tko_pb2.py
RUN rm artifact.tar.gz

# Remove Extras
RUN rm -rf client/deps/
RUN rm -rf client/site_tests/
RUN rm -rf moblab/
RUN rm -rf server/site_tests/
RUN rm -rf test_suites/
RUN rm -rf frontend/client/src/autotest/

# Set directory back to root
WORKDIR /
