# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/cros-registry/test-services/cros-test:prodTF

COPY --chown=chromeos-test:chromeos-test cros-test /usr/bin/

# Replace metadata with the latest version.
RUN rm -rf /tmp/test/metadata/*
COPY --chown=chromeos-test:chromeos-test tradefed_metadata.pb /tmp/test/metadata/
