# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/cros-registry/base-images/ubuntu:ubuntuProd
RUN apt-get update \
    && apt-get install -y curl

COPY pre_process_filter /usr/bin/