// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: inputprops.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto message which reflects the input properties of the build_wheels recipe.
// See more detailed description for each field there.
type InputProps struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Platforms    []string               `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Dryrun       bool                   `protobuf:"varint,2,opt,name=dryrun,proto3" json:"dryrun,omitempty"`
	Rebuild      bool                   `protobuf:"varint,3,opt,name=rebuild,proto3" json:"rebuild,omitempty"`
	Experimental bool                   `protobuf:"varint,4,opt,name=experimental,proto3" json:"experimental,omitempty"`
	// This field is accessed to determine if we mock the executor of dockerbuild
	// command - useful to dryrun dockerbuild in testing.
	ExperimentalDryrun bool `protobuf:"varint,5,opt,name=experimental_dryrun,json=experimentalDryrun,proto3" json:"experimental_dryrun,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InputProps) Reset() {
	*x = InputProps{}
	mi := &file_inputprops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputProps) ProtoMessage() {}

func (x *InputProps) ProtoReflect() protoreflect.Message {
	mi := &file_inputprops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputProps.ProtoReflect.Descriptor instead.
func (*InputProps) Descriptor() ([]byte, []int) {
	return file_inputprops_proto_rawDescGZIP(), []int{0}
}

func (x *InputProps) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *InputProps) GetDryrun() bool {
	if x != nil {
		return x.Dryrun
	}
	return false
}

func (x *InputProps) GetRebuild() bool {
	if x != nil {
		return x.Rebuild
	}
	return false
}

func (x *InputProps) GetExperimental() bool {
	if x != nil {
		return x.Experimental
	}
	return false
}

func (x *InputProps) GetExperimentalDryrun() bool {
	if x != nil {
		return x.ExperimentalDryrun
	}
	return false
}

var File_inputprops_proto protoreflect.FileDescriptor

var file_inputprops_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xb1, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x79, 0x72, 0x75, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x72, 0x75, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x13, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x72, 0x79, 0x72,
	0x75, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x44, 0x72, 0x79, 0x72, 0x75, 0x6e, 0x42, 0x24, 0x5a, 0x22,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x3b, 0x6d, 0x61,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_inputprops_proto_rawDescOnce sync.Once
	file_inputprops_proto_rawDescData []byte
)

func file_inputprops_proto_rawDescGZIP() []byte {
	file_inputprops_proto_rawDescOnce.Do(func() {
		file_inputprops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inputprops_proto_rawDesc), len(file_inputprops_proto_rawDesc)))
	})
	return file_inputprops_proto_rawDescData
}

var file_inputprops_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inputprops_proto_goTypes = []any{
	(*InputProps)(nil), // 0: main.InputProps
}
var file_inputprops_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inputprops_proto_init() }
func file_inputprops_proto_init() {
	if File_inputprops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inputprops_proto_rawDesc), len(file_inputprops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inputprops_proto_goTypes,
		DependencyIndexes: file_inputprops_proto_depIdxs,
		MessageInfos:      file_inputprops_proto_msgTypes,
	}.Build()
	File_inputprops_proto = out.File
	file_inputprops_proto_goTypes = nil
	file_inputprops_proto_depIdxs = nil
}
