// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package fleetconsole;

option go_package = "go.chromium.org/infra/fleetconsole/api/fleetconsolerpc;fleetconsolerpc";

import "google/protobuf/empty.proto";
import "go.chromium.org/infra/fleetconsole/api/fleetconsolerpc/common_types.proto";

service FleetConsole {
  // Ping does not send or receive any information. It just checks that the service is there.
  rpc Ping(PingRequest) returns (PingResponse);

  // PingBigQuery attempts to contact BigQuery service through Fleet Console. Useful for debugging.
  rpc PingBigQuery(PingBigQueryRequest) returns (PingBigQueryResponse);

  // PingDeviceManager attempts to contact DeviceManager through Fleet Console. Useful for debugging.
  rpc PingDeviceManager(PingDeviceManagerRequest) returns (PingDeviceManagerResponse);

  // PingUfs attempts to contact UFS through Fleet Console. Useful for debugging.
  rpc PingUfs(PingUfsRequest) returns (PingUfsResponse);

  // ListDevices managed by Device Manager.
  rpc ListDevices(ListDevicesRequest) returns (ListDevicesResponse) {};

  // GetDeviceDimensions provides overview of devices dimensions and their values
  rpc GetDeviceDimensions(google.protobuf.Empty) returns (GetDeviceDimensionsResponse);

  // CountDevices provides a count of the devices
  rpc CountDevices(CountDevicesRequest) returns (CountDevicesResponse) {};

  // RepopulateCache repopulates the cache, meant to be triggered by cron.
  rpc RepopulateCache(RepopulateCacheRequest) returns (RepopulateCacheResponse) {};

  // PingDB attempts to establish contact with the database and does nothing else.
  rpc PingDB(PingDBRequest) returns (PingDBResponse) {};

  // CleanExit just exits the current process.
  rpc CleanExit(CleanExitRequest) returns (CleanExitResponse) {};

  // ExportDevicesToCSV exports the devices in the csv format.
  rpc ExportDevicesToCSV(ExportDevicesToCSVRequest) returns (ExportDevicesToCSVResponse) {};

  // ************** RESOURCE REQUEST INSIGHTS *********************

  // ListResourceRequests returns Resource Requests provided by BigQuery
  rpc ListResourceRequests(ListResourceRequestsRequest) returns (ListResourceRequestsResponse) {};

  // CountResourceRequests provides counts for RRI summary header
  rpc CountResourceRequests(CountResourceRequestsRequest) returns (CountResourceRequestsResponse) {};

  // CountResourceRequests provides counts for RRI summary header
  rpc GetResourceRequestsMultiselectFilterValues(GetResourceRequestsMultiselectFilterValuesRequest) returns (GetResourceRequestsMultiselectFilterValuesResponse) {};
}

// PingRequest intentionally contains nothing.
message PingRequest {
}

// PingResponse intentionally contains nothing.
message PingResponse {
}

// PingBigQueryRequest intentionally contains nothing.
message PingBigQueryRequest {
}

// PingBigQueryResponse intentionally contains nothing.
message PingBigQueryResponse {
}

// PingDeviceManagerRequest intentionally contains nothing.
message PingDeviceManagerRequest {
}

// PingDeviceManagerResponse intentionally contains nothing.
message PingDeviceManagerResponse {
}

// PingUfsRequest intentionally contains nothing.
message PingUfsRequest {
}

// PingUfsResponse intentionally contains nothing.
message PingUfsResponse {
}

message Device {
  // In the case of VMs, device id could be the GCE instance name. For physical
  // DUTs we use the IDs we get from UFS.
  string id = 1;
  // dut_id is the asset tag for a Device
  string dut_id = 6;

  DeviceAddress address = 2;
  DeviceType type = 3;
  DeviceState state = 4;

  // // This proto contains per-DUT hardware relevant information including labels.
  DeviceSpec device_spec = 5;
}

message DeviceAddress {
  // IP address of the device.
  // For physical DUTs it can be a hostname.
  string host = 1;
  int32 port = 2;
}

enum DeviceType {
  DEVICE_TYPE_UNSPECIFIED = 0;
  DEVICE_TYPE_VIRTUAL = 1;
  DEVICE_TYPE_PHYSICAL = 2;
}

enum DeviceState {
  DEVICE_STATE_UNSPECIFIED = 0;
  // Default state.
  // Device is available to be leased.
  DEVICE_STATE_AVAILABLE = 1;
  // Device is leased.
  DEVICE_STATE_LEASED = 2;
}

message ListDevicesRequest {
  // The maximum number of devices to return. The service may return fewer than
  // this value. If unspecified, at most 1000 devices will be returned.
  int32 page_size = 1;

  // A page token, received from a previous `ListDevices` call. Provide this to
  // retrieve the subsequent page. Returns first page if omitted.
  //
  // When paginating, all other parameters provided to `ListDevices` must match
  // the call that provided the page token.
  string page_token = 2;

  string order_by = 3;

  // See: AIP-160 (https://google.aip.dev/160) for the syntax
  string filter = 4;
}

message ListDevicesResponse {
  // List of devices to be returned.
  repeated Device devices = 1;

  // A token, which can be sent as `page_token` to retrieve the next page. If
  // this field is omitted, there are no subsequent pages.
  string next_page_token = 2;
}

message DeviceSpec {
  // A map for labels used to request a matching device.
  map<string, LabelValues> labels = 1;
}

message GetDeviceDimensionsResponse {
  map<string, LabelValues> base_dimensions = 1;

  map<string, LabelValues> labels = 2;
}

message LabelValues {
  repeated string values = 1;
}

message CountDevicesRequest {
  // See: AIP-160 (https://google.aip.dev/160) for the syntax
  // Same filter format as ListDevicesRequest
  string filter = 1;
}

message CountDevicesResponse {
  int32 total = 1;

  TaskStateCounts task_state = 2;
  DeviceStateCounts device_state = 3;
}

message TaskStateCounts {
  int32 busy = 1;
  int32 idle = 2;
}

message DeviceStateCounts {
  int32 ready = 1;
  int32 need_manual_repair = 2;
  int32 need_repair = 3;
  int32 repair_failed = 4;
}

message RepopulateCacheRequest {}

message RepopulateCacheResponse {}

message PingDBRequest {}

message PingDBResponse {}

message CleanExitRequest {}

message CleanExitResponse {}

message ExportDevicesToCSVRequest {
  repeated Column columns = 1;
  string order_by = 2;

  // See: AIP-160 (https://google.aip.dev/160) for the syntax
  string filter = 3;

  // If specified will export only the devices with the specified ids.
  repeated string ids = 6;
}

message Column {
  string name = 1;
  string display_name = 2;
}

message ExportDevicesToCSVResponse {
  string csv_data = 1;
}

// ************** RESOURCE REQUEST INSIGHTS *********************

message ListResourceRequestsRequest {
  // The maximum number of Resource Requests to return. The service may return fewer than
  // this value. If unspecified, at most 50 Resource Requests will be returned.
  int32 page_size = 1;

  // A page token, received from a previous `ListResourceRequests` call. Provide this to
  // retrieve the subsequent page. Returns first page if omitted.
  //
  // When paginating, all other parameters provided to `ListResourceRequests` must match
  // the call that provided the page token.
  string page_token = 2;

  string order_by = 3;

  // See: AIP-160 (https://google.aip.dev/160) for the syntax
  string filter = 4;
}

message ListResourceRequestsResponse {
  // List of Resource Requests to be returned.
  repeated ResourceRequest resource_requests = 1;

  // A token, which can be sent as `page_token` to retrieve the next page. If
  // this field is omitted, there are no subsequent pages.
  string next_page_token = 2;
}

message ResourceRequest {
  enum Status {
    NOT_STARTED = 0;
    IN_PROGRESS = 1;
    COMPLETED = 2;
  }

  // The resource name of the resource request.
  // Format: resourceRequests/{rr_id}
  string name = 1;

  // The ID of the resource request.
  string rr_id = 2;

  // The details of the resource request.
  string resource_details = 3;

  // The procurement dates of the resource request.
  reserved 4;
  optional DateOnly procurement_target_start_date = 10;
  optional DateOnly procurement_actual_start_date = 11;
  optional DateOnly procurement_target_delivery_date = 12;
  optional DateOnly procurement_actual_delivery_date = 13;

  // The build dates of the resource request.
  reserved 5;
  optional DateOnly build_target_start_date = 14;
  optional DateOnly build_actual_start_date = 15;
  optional DateOnly build_target_delivery_date = 16;
  optional DateOnly build_actual_delivery_date = 17;

  // The QA dates of the resource request.
  reserved 6;
  optional DateOnly qa_target_start_date = 18;
  optional DateOnly qa_actual_start_date = 19;
  optional DateOnly qa_target_delivery_date = 20;
  optional DateOnly qa_actual_delivery_date = 21;

  // The config dates of the resource request.
  reserved 7;
  optional DateOnly config_target_start_date = 22;
  optional DateOnly config_actual_start_date = 23;
  optional DateOnly config_target_delivery_date = 24;
  optional DateOnly config_actual_delivery_date = 25;

  // Expected ETA for the resource request.
  optional DateOnly expected_eta = 8;

  // Status of the Fulfillment bug for the resource request.
  optional Status fulfillment_status = 9;
  optional Status material_sourcing_status = 26;
  optional Status build_status = 27;
  optional Status qa_status = 28;
  optional Status config_status = 29;
  optional string customer = 30;
  optional string resource_group = 31;
  optional string resource_name = 32;
  optional int32 accepted_quantity = 33;
  optional string criticality = 34;
  optional string request_approval = 35;
  optional string resource_pm = 36;
  optional string fulfillment_channel = 37;
  optional string execution_status = 38;
  repeated string resource_groups = 39;
}

message CountResourceRequestsRequest {
  // See: AIP-160 (https://google.aip.dev/160) for the syntax
  // Same filter format as ListDevicesRequest
  string filter = 1;
}

message CountResourceRequestsResponse {
  int32 total = 1;
  int32 in_progress = 2;
  int32 completed = 3;
  int32 material_sourcing = 4;
  int32 build = 5;
  int32 qa = 6;
  int32 config = 7;
}

message GetResourceRequestsMultiselectFilterValuesRequest {
}

message GetResourceRequestsMultiselectFilterValuesResponse {
  repeated string rr_ids = 1;
  repeated string resource_details = 2;
  repeated string material_sourcing_status = 3;
  repeated string build_status = 4;
  repeated string qa_status = 5;
  repeated string config_status = 6;
  repeated string customer = 7;
  repeated string resource_name = 8;
  repeated int32 accepted_quantity = 9;
  repeated string criticality = 10;
  repeated string request_approval = 11;
  repeated string resource_pm = 12;
  repeated string fulfillment_channel = 13;
  repeated string execution_status = 14;
  // Contains all unique string values from the 'resource_groups' (repeated) field
  // across all resource requests.
  repeated string resource_groups = 15;
}