// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: go.chromium.org/infra/fleetconsole/api/fleetconsolerpc/service.proto

package fleetconsolerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetConsole_Ping_FullMethodName                                       = "/fleetconsole.FleetConsole/Ping"
	FleetConsole_PingBigQuery_FullMethodName                               = "/fleetconsole.FleetConsole/PingBigQuery"
	FleetConsole_PingDeviceManager_FullMethodName                          = "/fleetconsole.FleetConsole/PingDeviceManager"
	FleetConsole_PingUfs_FullMethodName                                    = "/fleetconsole.FleetConsole/PingUfs"
	FleetConsole_LogFrontend_FullMethodName                                = "/fleetconsole.FleetConsole/LogFrontend"
	FleetConsole_ListDevices_FullMethodName                                = "/fleetconsole.FleetConsole/ListDevices"
	FleetConsole_GetDeviceDimensions_FullMethodName                        = "/fleetconsole.FleetConsole/GetDeviceDimensions"
	FleetConsole_CountDevices_FullMethodName                               = "/fleetconsole.FleetConsole/CountDevices"
	FleetConsole_RepopulateCache_FullMethodName                            = "/fleetconsole.FleetConsole/RepopulateCache"
	FleetConsole_PingDB_FullMethodName                                     = "/fleetconsole.FleetConsole/PingDB"
	FleetConsole_CleanExit_FullMethodName                                  = "/fleetconsole.FleetConsole/CleanExit"
	FleetConsole_ExportDevicesToCSV_FullMethodName                         = "/fleetconsole.FleetConsole/ExportDevicesToCSV"
	FleetConsole_ListResourceRequests_FullMethodName                       = "/fleetconsole.FleetConsole/ListResourceRequests"
	FleetConsole_CountResourceRequests_FullMethodName                      = "/fleetconsole.FleetConsole/CountResourceRequests"
	FleetConsole_GetResourceRequestsMultiselectFilterValues_FullMethodName = "/fleetconsole.FleetConsole/GetResourceRequestsMultiselectFilterValues"
	FleetConsole_UpdateAndroidDevices_FullMethodName                       = "/fleetconsole.FleetConsole/UpdateAndroidDevices"
	FleetConsole_ListRepairMetrics_FullMethodName                          = "/fleetconsole.FleetConsole/ListRepairMetrics"
	FleetConsole_CountRepairMetrics_FullMethodName                         = "/fleetconsole.FleetConsole/CountRepairMetrics"
	FleetConsole_GetRepairMetricsDimensions_FullMethodName                 = "/fleetconsole.FleetConsole/GetRepairMetricsDimensions"
)

// FleetConsoleClient is the client API for FleetConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetConsoleClient interface {
	// Ping does not send or receive any information. It just checks that the service is there.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// PingBigQuery attempts to contact BigQuery service through Fleet Console. Useful for debugging.
	PingBigQuery(ctx context.Context, in *PingBigQueryRequest, opts ...grpc.CallOption) (*PingBigQueryResponse, error)
	// PingDeviceManager attempts to contact DeviceManager through Fleet Console. Useful for debugging.
	PingDeviceManager(ctx context.Context, in *PingDeviceManagerRequest, opts ...grpc.CallOption) (*PingDeviceManagerResponse, error)
	// PingUfs attempts to contact UFS through Fleet Console. Useful for debugging.
	PingUfs(ctx context.Context, in *PingUfsRequest, opts ...grpc.CallOption) (*PingUfsResponse, error)
	// LogFrontend used to collect logs from the frontend
	LogFrontend(ctx context.Context, in *LogFrontendRequest, opts ...grpc.CallOption) (*LogFrontendResponse, error)
	// ListDevices managed by Device Manager.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// GetDeviceDimensions provides overview of devices dimensions and their values
	GetDeviceDimensions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDeviceDimensionsResponse, error)
	// CountDevices provides a count of the devices
	CountDevices(ctx context.Context, in *CountDevicesRequest, opts ...grpc.CallOption) (*CountDevicesResponse, error)
	// RepopulateCache repopulates the cache, meant to be triggered by cron.
	RepopulateCache(ctx context.Context, in *RepopulateCacheRequest, opts ...grpc.CallOption) (*RepopulateCacheResponse, error)
	// PingDB attempts to establish contact with the database and does nothing else.
	PingDB(ctx context.Context, in *PingDBRequest, opts ...grpc.CallOption) (*PingDBResponse, error)
	// CleanExit just exits the current process.
	CleanExit(ctx context.Context, in *CleanExitRequest, opts ...grpc.CallOption) (*CleanExitResponse, error)
	// ExportDevicesToCSV exports the devices in the csv format.
	ExportDevicesToCSV(ctx context.Context, in *ExportDevicesToCSVRequest, opts ...grpc.CallOption) (*ExportDevicesToCSVResponse, error)
	// ListResourceRequests returns Resource Requests provided by BigQuery
	ListResourceRequests(ctx context.Context, in *ListResourceRequestsRequest, opts ...grpc.CallOption) (*ListResourceRequestsResponse, error)
	// CountResourceRequests provides counts for RRI summary header
	CountResourceRequests(ctx context.Context, in *CountResourceRequestsRequest, opts ...grpc.CallOption) (*CountResourceRequestsResponse, error)
	// CountResourceRequests provides counts for RRI summary header
	GetResourceRequestsMultiselectFilterValues(ctx context.Context, in *GetResourceRequestsMultiselectFilterValuesRequest, opts ...grpc.CallOption) (*GetResourceRequestsMultiselectFilterValuesResponse, error)
	// ************** REPAIR METRICS *********************
	// UpdateAndroidDevices updates the android devices in the database.
	// Used to test the pubsub message.
	UpdateAndroidDevices(ctx context.Context, in *UpdateAndroidDevicesRequest, opts ...grpc.CallOption) (*UpdateAndroidDevicesResponse, error)
	ListRepairMetrics(ctx context.Context, in *ListRepairMetricsRequest, opts ...grpc.CallOption) (*ListRepairMetricsResponse, error)
	CountRepairMetrics(ctx context.Context, in *CountRepairMetricsRequest, opts ...grpc.CallOption) (*CountRepairMetricsResponse, error)
	GetRepairMetricsDimensions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRepairMetricsDimensionsResponse, error)
}

type fleetConsoleClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetConsoleClient(cc grpc.ClientConnInterface) FleetConsoleClient {
	return &fleetConsoleClient{cc}
}

func (c *fleetConsoleClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, FleetConsole_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) PingBigQuery(ctx context.Context, in *PingBigQueryRequest, opts ...grpc.CallOption) (*PingBigQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingBigQueryResponse)
	err := c.cc.Invoke(ctx, FleetConsole_PingBigQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) PingDeviceManager(ctx context.Context, in *PingDeviceManagerRequest, opts ...grpc.CallOption) (*PingDeviceManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingDeviceManagerResponse)
	err := c.cc.Invoke(ctx, FleetConsole_PingDeviceManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) PingUfs(ctx context.Context, in *PingUfsRequest, opts ...grpc.CallOption) (*PingUfsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingUfsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_PingUfs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) LogFrontend(ctx context.Context, in *LogFrontendRequest, opts ...grpc.CallOption) (*LogFrontendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogFrontendResponse)
	err := c.cc.Invoke(ctx, FleetConsole_LogFrontend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, FleetConsole_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) GetDeviceDimensions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDeviceDimensionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceDimensionsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_GetDeviceDimensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) CountDevices(ctx context.Context, in *CountDevicesRequest, opts ...grpc.CallOption) (*CountDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountDevicesResponse)
	err := c.cc.Invoke(ctx, FleetConsole_CountDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) RepopulateCache(ctx context.Context, in *RepopulateCacheRequest, opts ...grpc.CallOption) (*RepopulateCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepopulateCacheResponse)
	err := c.cc.Invoke(ctx, FleetConsole_RepopulateCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) PingDB(ctx context.Context, in *PingDBRequest, opts ...grpc.CallOption) (*PingDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingDBResponse)
	err := c.cc.Invoke(ctx, FleetConsole_PingDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) CleanExit(ctx context.Context, in *CleanExitRequest, opts ...grpc.CallOption) (*CleanExitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanExitResponse)
	err := c.cc.Invoke(ctx, FleetConsole_CleanExit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) ExportDevicesToCSV(ctx context.Context, in *ExportDevicesToCSVRequest, opts ...grpc.CallOption) (*ExportDevicesToCSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportDevicesToCSVResponse)
	err := c.cc.Invoke(ctx, FleetConsole_ExportDevicesToCSV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) ListResourceRequests(ctx context.Context, in *ListResourceRequestsRequest, opts ...grpc.CallOption) (*ListResourceRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceRequestsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_ListResourceRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) CountResourceRequests(ctx context.Context, in *CountResourceRequestsRequest, opts ...grpc.CallOption) (*CountResourceRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResourceRequestsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_CountResourceRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) GetResourceRequestsMultiselectFilterValues(ctx context.Context, in *GetResourceRequestsMultiselectFilterValuesRequest, opts ...grpc.CallOption) (*GetResourceRequestsMultiselectFilterValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceRequestsMultiselectFilterValuesResponse)
	err := c.cc.Invoke(ctx, FleetConsole_GetResourceRequestsMultiselectFilterValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) UpdateAndroidDevices(ctx context.Context, in *UpdateAndroidDevicesRequest, opts ...grpc.CallOption) (*UpdateAndroidDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAndroidDevicesResponse)
	err := c.cc.Invoke(ctx, FleetConsole_UpdateAndroidDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) ListRepairMetrics(ctx context.Context, in *ListRepairMetricsRequest, opts ...grpc.CallOption) (*ListRepairMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepairMetricsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_ListRepairMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) CountRepairMetrics(ctx context.Context, in *CountRepairMetricsRequest, opts ...grpc.CallOption) (*CountRepairMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountRepairMetricsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_CountRepairMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetConsoleClient) GetRepairMetricsDimensions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRepairMetricsDimensionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepairMetricsDimensionsResponse)
	err := c.cc.Invoke(ctx, FleetConsole_GetRepairMetricsDimensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetConsoleServer is the server API for FleetConsole service.
// All implementations must embed UnimplementedFleetConsoleServer
// for forward compatibility.
type FleetConsoleServer interface {
	// Ping does not send or receive any information. It just checks that the service is there.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PingBigQuery attempts to contact BigQuery service through Fleet Console. Useful for debugging.
	PingBigQuery(context.Context, *PingBigQueryRequest) (*PingBigQueryResponse, error)
	// PingDeviceManager attempts to contact DeviceManager through Fleet Console. Useful for debugging.
	PingDeviceManager(context.Context, *PingDeviceManagerRequest) (*PingDeviceManagerResponse, error)
	// PingUfs attempts to contact UFS through Fleet Console. Useful for debugging.
	PingUfs(context.Context, *PingUfsRequest) (*PingUfsResponse, error)
	// LogFrontend used to collect logs from the frontend
	LogFrontend(context.Context, *LogFrontendRequest) (*LogFrontendResponse, error)
	// ListDevices managed by Device Manager.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// GetDeviceDimensions provides overview of devices dimensions and their values
	GetDeviceDimensions(context.Context, *emptypb.Empty) (*GetDeviceDimensionsResponse, error)
	// CountDevices provides a count of the devices
	CountDevices(context.Context, *CountDevicesRequest) (*CountDevicesResponse, error)
	// RepopulateCache repopulates the cache, meant to be triggered by cron.
	RepopulateCache(context.Context, *RepopulateCacheRequest) (*RepopulateCacheResponse, error)
	// PingDB attempts to establish contact with the database and does nothing else.
	PingDB(context.Context, *PingDBRequest) (*PingDBResponse, error)
	// CleanExit just exits the current process.
	CleanExit(context.Context, *CleanExitRequest) (*CleanExitResponse, error)
	// ExportDevicesToCSV exports the devices in the csv format.
	ExportDevicesToCSV(context.Context, *ExportDevicesToCSVRequest) (*ExportDevicesToCSVResponse, error)
	// ListResourceRequests returns Resource Requests provided by BigQuery
	ListResourceRequests(context.Context, *ListResourceRequestsRequest) (*ListResourceRequestsResponse, error)
	// CountResourceRequests provides counts for RRI summary header
	CountResourceRequests(context.Context, *CountResourceRequestsRequest) (*CountResourceRequestsResponse, error)
	// CountResourceRequests provides counts for RRI summary header
	GetResourceRequestsMultiselectFilterValues(context.Context, *GetResourceRequestsMultiselectFilterValuesRequest) (*GetResourceRequestsMultiselectFilterValuesResponse, error)
	// ************** REPAIR METRICS *********************
	// UpdateAndroidDevices updates the android devices in the database.
	// Used to test the pubsub message.
	UpdateAndroidDevices(context.Context, *UpdateAndroidDevicesRequest) (*UpdateAndroidDevicesResponse, error)
	ListRepairMetrics(context.Context, *ListRepairMetricsRequest) (*ListRepairMetricsResponse, error)
	CountRepairMetrics(context.Context, *CountRepairMetricsRequest) (*CountRepairMetricsResponse, error)
	GetRepairMetricsDimensions(context.Context, *emptypb.Empty) (*GetRepairMetricsDimensionsResponse, error)
	mustEmbedUnimplementedFleetConsoleServer()
}

// UnimplementedFleetConsoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetConsoleServer struct{}

func (UnimplementedFleetConsoleServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFleetConsoleServer) PingBigQuery(context.Context, *PingBigQueryRequest) (*PingBigQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingBigQuery not implemented")
}
func (UnimplementedFleetConsoleServer) PingDeviceManager(context.Context, *PingDeviceManagerRequest) (*PingDeviceManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingDeviceManager not implemented")
}
func (UnimplementedFleetConsoleServer) PingUfs(context.Context, *PingUfsRequest) (*PingUfsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingUfs not implemented")
}
func (UnimplementedFleetConsoleServer) LogFrontend(context.Context, *LogFrontendRequest) (*LogFrontendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogFrontend not implemented")
}
func (UnimplementedFleetConsoleServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedFleetConsoleServer) GetDeviceDimensions(context.Context, *emptypb.Empty) (*GetDeviceDimensionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceDimensions not implemented")
}
func (UnimplementedFleetConsoleServer) CountDevices(context.Context, *CountDevicesRequest) (*CountDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountDevices not implemented")
}
func (UnimplementedFleetConsoleServer) RepopulateCache(context.Context, *RepopulateCacheRequest) (*RepopulateCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepopulateCache not implemented")
}
func (UnimplementedFleetConsoleServer) PingDB(context.Context, *PingDBRequest) (*PingDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingDB not implemented")
}
func (UnimplementedFleetConsoleServer) CleanExit(context.Context, *CleanExitRequest) (*CleanExitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanExit not implemented")
}
func (UnimplementedFleetConsoleServer) ExportDevicesToCSV(context.Context, *ExportDevicesToCSVRequest) (*ExportDevicesToCSVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportDevicesToCSV not implemented")
}
func (UnimplementedFleetConsoleServer) ListResourceRequests(context.Context, *ListResourceRequestsRequest) (*ListResourceRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceRequests not implemented")
}
func (UnimplementedFleetConsoleServer) CountResourceRequests(context.Context, *CountResourceRequestsRequest) (*CountResourceRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountResourceRequests not implemented")
}
func (UnimplementedFleetConsoleServer) GetResourceRequestsMultiselectFilterValues(context.Context, *GetResourceRequestsMultiselectFilterValuesRequest) (*GetResourceRequestsMultiselectFilterValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceRequestsMultiselectFilterValues not implemented")
}
func (UnimplementedFleetConsoleServer) UpdateAndroidDevices(context.Context, *UpdateAndroidDevicesRequest) (*UpdateAndroidDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAndroidDevices not implemented")
}
func (UnimplementedFleetConsoleServer) ListRepairMetrics(context.Context, *ListRepairMetricsRequest) (*ListRepairMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepairMetrics not implemented")
}
func (UnimplementedFleetConsoleServer) CountRepairMetrics(context.Context, *CountRepairMetricsRequest) (*CountRepairMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountRepairMetrics not implemented")
}
func (UnimplementedFleetConsoleServer) GetRepairMetricsDimensions(context.Context, *emptypb.Empty) (*GetRepairMetricsDimensionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepairMetricsDimensions not implemented")
}
func (UnimplementedFleetConsoleServer) mustEmbedUnimplementedFleetConsoleServer() {}
func (UnimplementedFleetConsoleServer) testEmbeddedByValue()                      {}

// UnsafeFleetConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetConsoleServer will
// result in compilation errors.
type UnsafeFleetConsoleServer interface {
	mustEmbedUnimplementedFleetConsoleServer()
}

func RegisterFleetConsoleServer(s grpc.ServiceRegistrar, srv FleetConsoleServer) {
	// If the following call pancis, it indicates UnimplementedFleetConsoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetConsole_ServiceDesc, srv)
}

func _FleetConsole_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_PingBigQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingBigQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).PingBigQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_PingBigQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).PingBigQuery(ctx, req.(*PingBigQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_PingDeviceManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingDeviceManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).PingDeviceManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_PingDeviceManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).PingDeviceManager(ctx, req.(*PingDeviceManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_PingUfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingUfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).PingUfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_PingUfs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).PingUfs(ctx, req.(*PingUfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_LogFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogFrontendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).LogFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_LogFrontend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).LogFrontend(ctx, req.(*LogFrontendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_GetDeviceDimensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).GetDeviceDimensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_GetDeviceDimensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).GetDeviceDimensions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_CountDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).CountDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_CountDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).CountDevices(ctx, req.(*CountDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_RepopulateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepopulateCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).RepopulateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_RepopulateCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).RepopulateCache(ctx, req.(*RepopulateCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_PingDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).PingDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_PingDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).PingDB(ctx, req.(*PingDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_CleanExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).CleanExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_CleanExit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).CleanExit(ctx, req.(*CleanExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_ExportDevicesToCSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDevicesToCSVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).ExportDevicesToCSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_ExportDevicesToCSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).ExportDevicesToCSV(ctx, req.(*ExportDevicesToCSVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_ListResourceRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).ListResourceRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_ListResourceRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).ListResourceRequests(ctx, req.(*ListResourceRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_CountResourceRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountResourceRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).CountResourceRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_CountResourceRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).CountResourceRequests(ctx, req.(*CountResourceRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_GetResourceRequestsMultiselectFilterValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequestsMultiselectFilterValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).GetResourceRequestsMultiselectFilterValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_GetResourceRequestsMultiselectFilterValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).GetResourceRequestsMultiselectFilterValues(ctx, req.(*GetResourceRequestsMultiselectFilterValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_UpdateAndroidDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndroidDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).UpdateAndroidDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_UpdateAndroidDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).UpdateAndroidDevices(ctx, req.(*UpdateAndroidDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_ListRepairMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepairMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).ListRepairMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_ListRepairMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).ListRepairMetrics(ctx, req.(*ListRepairMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_CountRepairMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRepairMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).CountRepairMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_CountRepairMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).CountRepairMetrics(ctx, req.(*CountRepairMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetConsole_GetRepairMetricsDimensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).GetRepairMetricsDimensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_GetRepairMetricsDimensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).GetRepairMetricsDimensions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetConsole_ServiceDesc is the grpc.ServiceDesc for FleetConsole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetConsole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetconsole.FleetConsole",
	HandlerType: (*FleetConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FleetConsole_Ping_Handler,
		},
		{
			MethodName: "PingBigQuery",
			Handler:    _FleetConsole_PingBigQuery_Handler,
		},
		{
			MethodName: "PingDeviceManager",
			Handler:    _FleetConsole_PingDeviceManager_Handler,
		},
		{
			MethodName: "PingUfs",
			Handler:    _FleetConsole_PingUfs_Handler,
		},
		{
			MethodName: "LogFrontend",
			Handler:    _FleetConsole_LogFrontend_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _FleetConsole_ListDevices_Handler,
		},
		{
			MethodName: "GetDeviceDimensions",
			Handler:    _FleetConsole_GetDeviceDimensions_Handler,
		},
		{
			MethodName: "CountDevices",
			Handler:    _FleetConsole_CountDevices_Handler,
		},
		{
			MethodName: "RepopulateCache",
			Handler:    _FleetConsole_RepopulateCache_Handler,
		},
		{
			MethodName: "PingDB",
			Handler:    _FleetConsole_PingDB_Handler,
		},
		{
			MethodName: "CleanExit",
			Handler:    _FleetConsole_CleanExit_Handler,
		},
		{
			MethodName: "ExportDevicesToCSV",
			Handler:    _FleetConsole_ExportDevicesToCSV_Handler,
		},
		{
			MethodName: "ListResourceRequests",
			Handler:    _FleetConsole_ListResourceRequests_Handler,
		},
		{
			MethodName: "CountResourceRequests",
			Handler:    _FleetConsole_CountResourceRequests_Handler,
		},
		{
			MethodName: "GetResourceRequestsMultiselectFilterValues",
			Handler:    _FleetConsole_GetResourceRequestsMultiselectFilterValues_Handler,
		},
		{
			MethodName: "UpdateAndroidDevices",
			Handler:    _FleetConsole_UpdateAndroidDevices_Handler,
		},
		{
			MethodName: "ListRepairMetrics",
			Handler:    _FleetConsole_ListRepairMetrics_Handler,
		},
		{
			MethodName: "CountRepairMetrics",
			Handler:    _FleetConsole_CountRepairMetrics_Handler,
		},
		{
			MethodName: "GetRepairMetricsDimensions",
			Handler:    _FleetConsole_GetRepairMetricsDimensions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.chromium.org/infra/fleetconsole/api/fleetconsolerpc/service.proto",
}
